'use strict';

function noop() { }
function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}
function is_function(thing) {
    return typeof thing === 'function';
}
function safe_not_equal(a, b) {
    return a != a ? b == b : a !== b || ((a && typeof a === 'object') || typeof a === 'function');
}
function subscribe(store, ...callbacks) {
    if (store == null) {
        return noop;
    }
    const unsub = store.subscribe(...callbacks);
    return unsub.unsubscribe ? () => unsub.unsubscribe() : unsub;
}
function null_to_empty(value) {
    return value == null ? '' : value;
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
function get_current_component() {
    if (!current_component)
        throw new Error('Function called outside component initialization');
    return current_component;
}
function onMount(fn) {
    get_current_component().$$.on_mount.push(fn);
}
const escaped = {
    '"': '&quot;',
    "'": '&#39;',
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;'
};
function escape(html) {
    return String(html).replace(/["'&<>]/g, match => escaped[match]);
}
function each(items, fn) {
    let str = '';
    for (let i = 0; i < items.length; i += 1) {
        str += fn(items[i], i);
    }
    return str;
}
function validate_component(component, name) {
    if (!component || !component.$$render) {
        if (name === 'svelte:component')
            name += ' this={...}';
        throw new Error(`<${name}> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`);
    }
    return component;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots, context) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : context || []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, { $$slots = {}, context = new Map() } = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, $$slots, context);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}
function add_attribute(name, value, boolean) {
    if (value == null || (boolean && !value))
        return '';
    return ` ${name}${value === true ? '' : `=${typeof value === 'string' ? JSON.stringify(escape(value)) : `"${value}"`}`}`;
}

/* node_modules/creditdesign-svelte-components/src/components/Box/index.svelte generated by Svelte v3.38.3 */

const css$j = {
	code: ":root{--box-space--global:var(--s-1)}.box.svelte-dzdna{--box-space--component:initial;--box-space:var(--box-space--component, var(--box-space--global, 1rem));padding:1rem;padding:var(--box-space)}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  export let boxSpace = \\\"\\\";\\n\\n  let boxSpaceComponent = boxSpace.length\\n    ? `--box-space--component: ${boxSpace};`\\n    : \\\"\\\";\\n</script>\\n\\n<style>\\n  :global(:root) {\\n    --box-space--global: var(--s-1);\\n  }\\n\\n  .box {\\n    --box-space--component: initial;\\n    --box-space: var(--box-space--component, var(--box-space--global, 1rem));\\n\\n    padding: 1rem;\\n    padding: var(--box-space);\\n  }\\n</style>\\n\\n<div class=\\\"box\\\" style=\\\"{boxSpaceComponent}\\\">\\n  <slot />\\n</div>\\n\"],\"names\":[],\"mappings\":\"AASU,KAAK,AAAE,CAAC,AACd,mBAAmB,CAAE,UAAU,AACjC,CAAC,AAED,IAAI,aAAC,CAAC,AACJ,sBAAsB,CAAE,OAAO,CAC/B,WAAW,CAAE,2DAA2D,CAExE,OAAO,CAAE,IAAI,CACb,OAAO,CAAE,IAAI,WAAW,CAAC,AAC3B,CAAC\"}"
};

const Box = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { boxSpace = "" } = $$props;

	let boxSpaceComponent = boxSpace.length
	? `--box-space--component: ${boxSpace};`
	: "";

	if ($$props.boxSpace === void 0 && $$bindings.boxSpace && boxSpace !== void 0) $$bindings.boxSpace(boxSpace);
	$$result.css.add(css$j);
	return `<div class="${"box svelte-dzdna"}"${add_attribute("style", boxSpaceComponent, 0)}>${slots.default ? slots.default({}) : ``}</div>`;
});

/* node_modules/creditdesign-svelte-components/src/components/Center/index.svelte generated by Svelte v3.38.3 */

const css$i = {
	code: ":root{--center-measure--global:var(--measure);--center-space--global:var(--s-1)}.center.svelte-l22bbz{--center-measure--component:initial;--center-space--component:initial;--center-measure:var(\n      --center-measure--component,\n      var(--center-measure--global, 60ch)\n    );--center-space:var(\n      --center-space--component,\n      var(--center-space--global, 1rem)\n    );box-sizing:content-box;max-width:60ch;max-width:var(--center-measure);padding-right:1rem;padding-right:var(--center-space);padding-left:1rem;padding-left:var(--center-space);margin-right:auto;margin-left:auto}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  export let centerMeasure = \\\"\\\";\\n  export let centerSpace = \\\"\\\";\\n\\n  let centerMeasureComponent = centerMeasure.length\\n    ? `--center-measure--component: ${centerMeasure};`\\n    : \\\"\\\";\\n  let centerSpaceComponent = centerSpace.length\\n    ? `--center-space--component: ${centerSpace};`\\n    : \\\"\\\";\\n  let style = `${centerMeasureComponent} ${centerSpaceComponent}`;\\n</script>\\n\\n<style>\\n  :global(:root) {\\n    --center-measure--global: var(--measure);\\n    --center-space--global: var(--s-1);\\n  }\\n\\n  .center {\\n    --center-measure--component: initial;\\n    --center-space--component: initial;\\n    --center-measure: var(\\n      --center-measure--component,\\n      var(--center-measure--global, 60ch)\\n    );\\n    --center-space: var(\\n      --center-space--component,\\n      var(--center-space--global, 1rem)\\n    );\\n\\n    box-sizing: content-box;\\n    max-width: 60ch;\\n    max-width: var(--center-measure);\\n    padding-right: 1rem;\\n    padding-right: var(--center-space);\\n    padding-left: 1rem;\\n    padding-left: var(--center-space);\\n    margin-right: auto;\\n    margin-left: auto;\\n  }\\n</style>\\n\\n<div class=\\\"center\\\" style=\\\"{style}\\\">\\n  <slot />\\n</div>\\n\"],\"names\":[],\"mappings\":\"AAcU,KAAK,AAAE,CAAC,AACd,wBAAwB,CAAE,cAAc,CACxC,sBAAsB,CAAE,UAAU,AACpC,CAAC,AAED,OAAO,cAAC,CAAC,AACP,2BAA2B,CAAE,OAAO,CACpC,yBAAyB,CAAE,OAAO,CAClC,gBAAgB,CAAE;;;KAGjB,CACD,cAAc,CAAE;;;KAGf,CAED,UAAU,CAAE,WAAW,CACvB,SAAS,CAAE,IAAI,CACf,SAAS,CAAE,IAAI,gBAAgB,CAAC,CAChC,aAAa,CAAE,IAAI,CACnB,aAAa,CAAE,IAAI,cAAc,CAAC,CAClC,YAAY,CAAE,IAAI,CAClB,YAAY,CAAE,IAAI,cAAc,CAAC,CACjC,YAAY,CAAE,IAAI,CAClB,WAAW,CAAE,IAAI,AACnB,CAAC\"}"
};

const Center = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { centerMeasure = "" } = $$props;
	let { centerSpace = "" } = $$props;

	let centerMeasureComponent = centerMeasure.length
	? `--center-measure--component: ${centerMeasure};`
	: "";

	let centerSpaceComponent = centerSpace.length
	? `--center-space--component: ${centerSpace};`
	: "";

	let style = `${centerMeasureComponent} ${centerSpaceComponent}`;
	if ($$props.centerMeasure === void 0 && $$bindings.centerMeasure && centerMeasure !== void 0) $$bindings.centerMeasure(centerMeasure);
	if ($$props.centerSpace === void 0 && $$bindings.centerSpace && centerSpace !== void 0) $$bindings.centerSpace(centerSpace);
	$$result.css.add(css$i);
	return `<div class="${"center svelte-l22bbz"}"${add_attribute("style", style, 0)}>${slots.default ? slots.default({}) : ``}</div>`;
});

/* node_modules/creditdesign-svelte-components/src/components/ClusterList/index.svelte generated by Svelte v3.38.3 */

const css$h = {
	code: ":root{--cluster-space--global:var(--s-1);--cluster-justify-content--global:flex-start}.cluster--list.svelte-1dbwytq{--cluster-justify-content--component:initial;--cluster-space--component:initial;--cluster-justify-content:var(\n      --cluster-justify-content--component,\n      var(--cluster-justify-content--global)\n    );--cluster-space:var(\n      --cluster-space--component,\n      var(--cluster-space--global)\n    );overflow:hidden}.cluster--list__inner.svelte-1dbwytq{display:flex;flex-wrap:wrap;align-items:center;justify-content:var(--cluster-justify-content);margin:1rem;margin:calc(var(--cluster-space) / 2 * -1)}.cluster--list__inner > *{margin:calc(var(--cluster-space) / 2)}.cluster--list__split-after{flex-grow:1}.cluster--list ul{max-width:none;padding:0;list-style:none}.cluster--list li{max-width:none;padding:0}.cluster--list__inner > .grow{flex-grow:2}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  export let clusterJustifyContent = \\\"\\\";\\n  export let clusterSpace = \\\"\\\";\\n\\n  let clusterJustifyContentComponent = clusterJustifyContent.length\\n    ? `--cluster-justify-content--component: ${clusterJustifyContent};`\\n    : \\\"\\\";\\n  let clusterSpaceComponent = clusterSpace.length\\n    ? `--cluster-space--component: ${clusterSpace};`\\n    : \\\"\\\";\\n  let style = `${clusterJustifyContentComponent} ${clusterSpaceComponent}`;\\n</script>\\n\\n<style>\\n  :global(:root) {\\n    --cluster-space--global: var(--s-1);\\n    --cluster-justify-content--global: flex-start;\\n  }\\n\\n  .cluster--list {\\n    --cluster-justify-content--component: initial;\\n    --cluster-space--component: initial;\\n    --cluster-justify-content: var(\\n      --cluster-justify-content--component,\\n      var(--cluster-justify-content--global)\\n    );\\n    --cluster-space: var(\\n      --cluster-space--component,\\n      var(--cluster-space--global)\\n    );\\n\\n    overflow: hidden;\\n  }\\n\\n  .cluster--list__inner {\\n    display: flex;\\n    flex-wrap: wrap;\\n    align-items: center;\\n    justify-content: var(--cluster-justify-content);\\n    margin: 1rem;\\n    margin: calc(var(--cluster-space) / 2 * -1);\\n  }\\n\\n  :global(.cluster--list__inner > *) {\\n    margin: calc(var(--cluster-space) / 2);\\n  }\\n\\n  :global(.cluster--list__split-after) {\\n    flex-grow: 1;\\n  }\\n\\n  :global(.cluster--list ul) {\\n    max-width: none;\\n    padding: 0;\\n    list-style: none;\\n  }\\n\\n  :global(.cluster--list li) {\\n    max-width: none;\\n    padding: 0;\\n  }\\n\\n  :global(.cluster--list__inner > .grow) {\\n    flex-grow: 2;\\n  }\\n</style>\\n\\n<div class=\\\"cluster--list\\\" style=\\\"{style}\\\">\\n  <ul class=\\\"cluster--list__inner\\\">\\n    <slot />\\n  </ul>\\n</div>\\n\"],\"names\":[],\"mappings\":\"AAcU,KAAK,AAAE,CAAC,AACd,uBAAuB,CAAE,UAAU,CACnC,iCAAiC,CAAE,UAAU,AAC/C,CAAC,AAED,cAAc,eAAC,CAAC,AACd,oCAAoC,CAAE,OAAO,CAC7C,0BAA0B,CAAE,OAAO,CACnC,yBAAyB,CAAE;;;KAG1B,CACD,eAAe,CAAE;;;KAGhB,CAED,QAAQ,CAAE,MAAM,AAClB,CAAC,AAED,qBAAqB,eAAC,CAAC,AACrB,OAAO,CAAE,IAAI,CACb,SAAS,CAAE,IAAI,CACf,WAAW,CAAE,MAAM,CACnB,eAAe,CAAE,IAAI,yBAAyB,CAAC,CAC/C,MAAM,CAAE,IAAI,CACZ,MAAM,CAAE,KAAK,IAAI,eAAe,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,EAAE,CAAC,AAC7C,CAAC,AAEO,yBAAyB,AAAE,CAAC,AAClC,MAAM,CAAE,KAAK,IAAI,eAAe,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,AACxC,CAAC,AAEO,2BAA2B,AAAE,CAAC,AACpC,SAAS,CAAE,CAAC,AACd,CAAC,AAEO,iBAAiB,AAAE,CAAC,AAC1B,SAAS,CAAE,IAAI,CACf,OAAO,CAAE,CAAC,CACV,UAAU,CAAE,IAAI,AAClB,CAAC,AAEO,iBAAiB,AAAE,CAAC,AAC1B,SAAS,CAAE,IAAI,CACf,OAAO,CAAE,CAAC,AACZ,CAAC,AAEO,6BAA6B,AAAE,CAAC,AACtC,SAAS,CAAE,CAAC,AACd,CAAC\"}"
};

const ClusterList = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { clusterJustifyContent = "" } = $$props;
	let { clusterSpace = "" } = $$props;

	let clusterJustifyContentComponent = clusterJustifyContent.length
	? `--cluster-justify-content--component: ${clusterJustifyContent};`
	: "";

	let clusterSpaceComponent = clusterSpace.length
	? `--cluster-space--component: ${clusterSpace};`
	: "";

	let style = `${clusterJustifyContentComponent} ${clusterSpaceComponent}`;
	if ($$props.clusterJustifyContent === void 0 && $$bindings.clusterJustifyContent && clusterJustifyContent !== void 0) $$bindings.clusterJustifyContent(clusterJustifyContent);
	if ($$props.clusterSpace === void 0 && $$bindings.clusterSpace && clusterSpace !== void 0) $$bindings.clusterSpace(clusterSpace);
	$$result.css.add(css$h);
	return `<div class="${"cluster--list svelte-1dbwytq"}"${add_attribute("style", style, 0)}><ul class="${"cluster--list__inner svelte-1dbwytq"}">${slots.default ? slots.default({}) : ``}</ul></div>`;
});

/* node_modules/creditdesign-svelte-components/src/components/Stack/index.svelte generated by Svelte v3.38.3 */

const css$g = {
	code: ":root{--stack-space--global:var(--s-1)}.stack.svelte-tewrqr{--stack-space--component:initial;--stack-space:var(--stack-space--component, var(--stack-space--global));display:flex;flex-direction:column;justify-content:flex-start}.stack > *{margin:0}.stack > * + *{margin-top:1rem;margin-top:var(--stack-space)}.stack:only-child{height:100%}.stack > .stack__split-after{margin-bottom:auto}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  export let stackSpace = \\\"\\\";\\n\\n  let stackSpaceComponent = stackSpace.length\\n    ? `--stack-space--component: ${stackSpace};`\\n    : \\\"\\\";\\n</script>\\n\\n<style>\\n  :global(:root) {\\n    --stack-space--global: var(--s-1);\\n  }\\n\\n  .stack {\\n    --stack-space--component: initial;\\n    --stack-space: var(--stack-space--component, var(--stack-space--global));\\n\\n    display: flex;\\n    flex-direction: column;\\n    justify-content: flex-start;\\n  }\\n\\n  :global(.stack > *) {\\n    margin: 0;\\n  }\\n\\n  :global(.stack > * + *) {\\n    margin-top: 1rem;\\n    margin-top: var(--stack-space);\\n  }\\n\\n  :global(.stack:only-child) {\\n    height: 100%;\\n  }\\n\\n  :global(.stack > .stack__split-after) {\\n    margin-bottom: auto;\\n  }\\n</style>\\n\\n<div>\\n  <div class=\\\"stack\\\" style=\\\"{stackSpaceComponent}\\\">\\n    <slot />\\n  </div>\\n</div>\\n\"],\"names\":[],\"mappings\":\"AASU,KAAK,AAAE,CAAC,AACd,qBAAqB,CAAE,UAAU,AACnC,CAAC,AAED,MAAM,cAAC,CAAC,AACN,wBAAwB,CAAE,OAAO,CACjC,aAAa,CAAE,yDAAyD,CAExE,OAAO,CAAE,IAAI,CACb,cAAc,CAAE,MAAM,CACtB,eAAe,CAAE,UAAU,AAC7B,CAAC,AAEO,UAAU,AAAE,CAAC,AACnB,MAAM,CAAE,CAAC,AACX,CAAC,AAEO,cAAc,AAAE,CAAC,AACvB,UAAU,CAAE,IAAI,CAChB,UAAU,CAAE,IAAI,aAAa,CAAC,AAChC,CAAC,AAEO,iBAAiB,AAAE,CAAC,AAC1B,MAAM,CAAE,IAAI,AACd,CAAC,AAEO,4BAA4B,AAAE,CAAC,AACrC,aAAa,CAAE,IAAI,AACrB,CAAC\"}"
};

const Stack = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { stackSpace = "" } = $$props;

	let stackSpaceComponent = stackSpace.length
	? `--stack-space--component: ${stackSpace};`
	: "";

	if ($$props.stackSpace === void 0 && $$bindings.stackSpace && stackSpace !== void 0) $$bindings.stackSpace(stackSpace);
	$$result.css.add(css$g);
	return `<div><div class="${"stack svelte-tewrqr"}"${add_attribute("style", stackSpaceComponent, 0)}>${slots.default ? slots.default({}) : ``}</div></div>`;
});

/**
 * Given a valid unix time stamp return a date string
 * if format is "day-month-year" return formatted as "22 March 2020"
 * if format is "iso-string" return as a a valid global date and time string
 * i.e. 2022-03-29T07:59:29.000Z
 *
 * @param {*} unixTimeStamp
 * @param {*} format
 * @returns
 */
const formatDate = (unixTimeStamp, format = "day-month-year") => {
  const date = new Date(parseInt(unixTimeStamp, 10) * 1000);
  const year = date.getFullYear();
  const month = date.toLocaleDateString("en", { month: "long" });
  const day = date.getDate();

  if (format === "iso-string") {
    return date.toISOString();
  }

  return `${day} ${month} ${year}`;
};

/* node_modules/nature-immersive-svelte-components/src/components/Heading/index.svelte generated by Svelte v3.38.3 */

const css$f = {
	code: ".heading.svelte-19qhu5i{text-align:center}h1.svelte-19qhu5i,p.svelte-19qhu5i{max-width:none}.stand-first.svelte-19qhu5i{font-size:var(--font-size-big-1)}time.svelte-19qhu5i{max-width:none;line-height:1rem;letter-spacing:0.05em}@media(max-width: 740px){h1.svelte-19qhu5i{font-size:var(--font-size-big-2)}.stand-first.svelte-19qhu5i{font-size:var(--font-size-base)}}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  import { Center, Stack } from \\\"creditdesign-svelte-components\\\";\\n\\n  import formatDate from \\\"../utils/format-date.js\\\";\\n\\n  export let articleData;\\n  export let className = \\\"\\\";\\n  export let maxWidth = \\\"var(--measure-big)\\\";\\n  /**\\n   * Padding to left and right of the heading\\n   */\\n  export let centerSpace = \\\"0\\\";\\n  /**\\n   * Space between head and stand block and bylines and date block\\n   */\\n  export let headAndCreditsStackSpace = \\\"var(--s2)\\\";\\n  export let headStandStackSpace = \\\"var(--s2)\\\";\\n  export let creditsStackSpace = \\\"var(--s-3)\\\";\\n\\n  let { author, headline, photographer, publishedAt, stand } = articleData;\\n</script>\\n\\n<style>\\n  .heading {\\n    text-align: center;\\n  }\\n\\n  h1,\\n  p {\\n    max-width: none;\\n  }\\n\\n  .stand-first {\\n    font-size: var(--font-size-big-1);\\n  }\\n\\n  time {\\n    max-width: none;\\n\\n    /* Even out the line height for the date */\\n\\n    line-height: 1rem;\\n    letter-spacing: 0.05em;\\n  }\\n\\n  @media (max-width: 740px) {\\n    h1 {\\n      font-size: var(--font-size-big-2);\\n    }\\n\\n    .stand-first {\\n      font-size: var(--font-size-base);\\n    }\\n  }\\n</style>\\n\\n<div class={`heading ${className}`}>\\n  <Center centerMeasure={maxWidth} {centerSpace}>\\n    <Stack stackSpace={headAndCreditsStackSpace}>\\n      <Stack stackSpace={headStandStackSpace}>\\n        <h1 class=\\\"letter-spacing:tight\\\">\\n          {@html headline}\\n        </h1>\\n        <p class=\\\"stand-first\\\">\\n          {@html stand}\\n        </p>\\n      </Stack>\\n\\n      {#if author || photographer || publishedAt}\\n        <Stack stackSpace={creditsStackSpace}>\\n          {#if author}\\n            <p class=\\\"author font-weight:bold\\\">\\n              {@html author}\\n            </p>\\n          {/if}\\n          {#if photographer}\\n            <p class=\\\"photographer font-weight:bold\\\">\\n              {@html photographer}\\n            </p>\\n          {/if}\\n\\n          {#if publishedAt}\\n            <time\\n              class=\\\"font-family:sans-serif font-size:small\\n              text-transform:uppercase\\\"\\n              itemProp=\\\"datePublished\\\"\\n              dateTime={formatDate(publishedAt, \\\"iso-string\\\")}\\n            >\\n              {formatDate(publishedAt, \\\"day-month-year\\\")}\\n            </time>\\n          {/if}\\n        </Stack>\\n      {/if}\\n    </Stack>\\n  </Center>\\n</div>\\n\"],\"names\":[],\"mappings\":\"AAuBE,QAAQ,eAAC,CAAC,AACR,UAAU,CAAE,MAAM,AACpB,CAAC,AAED,iBAAE,CACF,CAAC,eAAC,CAAC,AACD,SAAS,CAAE,IAAI,AACjB,CAAC,AAED,YAAY,eAAC,CAAC,AACZ,SAAS,CAAE,IAAI,iBAAiB,CAAC,AACnC,CAAC,AAED,IAAI,eAAC,CAAC,AACJ,SAAS,CAAE,IAAI,CAIf,WAAW,CAAE,IAAI,CACjB,cAAc,CAAE,MAAM,AACxB,CAAC,AAED,MAAM,AAAC,YAAY,KAAK,CAAC,AAAC,CAAC,AACzB,EAAE,eAAC,CAAC,AACF,SAAS,CAAE,IAAI,iBAAiB,CAAC,AACnC,CAAC,AAED,YAAY,eAAC,CAAC,AACZ,SAAS,CAAE,IAAI,gBAAgB,CAAC,AAClC,CAAC,AACH,CAAC\"}"
};

const Heading = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { articleData } = $$props;
	let { className = "" } = $$props;
	let { maxWidth = "var(--measure-big)" } = $$props;
	let { centerSpace = "0" } = $$props;
	let { headAndCreditsStackSpace = "var(--s2)" } = $$props;
	let { headStandStackSpace = "var(--s2)" } = $$props;
	let { creditsStackSpace = "var(--s-3)" } = $$props;
	let { author, headline, photographer, publishedAt, stand } = articleData;
	if ($$props.articleData === void 0 && $$bindings.articleData && articleData !== void 0) $$bindings.articleData(articleData);
	if ($$props.className === void 0 && $$bindings.className && className !== void 0) $$bindings.className(className);
	if ($$props.maxWidth === void 0 && $$bindings.maxWidth && maxWidth !== void 0) $$bindings.maxWidth(maxWidth);
	if ($$props.centerSpace === void 0 && $$bindings.centerSpace && centerSpace !== void 0) $$bindings.centerSpace(centerSpace);
	if ($$props.headAndCreditsStackSpace === void 0 && $$bindings.headAndCreditsStackSpace && headAndCreditsStackSpace !== void 0) $$bindings.headAndCreditsStackSpace(headAndCreditsStackSpace);
	if ($$props.headStandStackSpace === void 0 && $$bindings.headStandStackSpace && headStandStackSpace !== void 0) $$bindings.headStandStackSpace(headStandStackSpace);
	if ($$props.creditsStackSpace === void 0 && $$bindings.creditsStackSpace && creditsStackSpace !== void 0) $$bindings.creditsStackSpace(creditsStackSpace);
	$$result.css.add(css$f);

	return `<div class="${escape(null_to_empty(`heading ${className}`)) + " svelte-19qhu5i"}">${validate_component(Center, "Center").$$render($$result, { centerMeasure: maxWidth, centerSpace }, {}, {
		default: () => `${validate_component(Stack, "Stack").$$render($$result, { stackSpace: headAndCreditsStackSpace }, {}, {
			default: () => `${validate_component(Stack, "Stack").$$render($$result, { stackSpace: headStandStackSpace }, {}, {
				default: () => `<h1 class="${"letter-spacing:tight svelte-19qhu5i"}">${headline}</h1>
        <p class="${"stand-first svelte-19qhu5i"}">${stand}</p>`
			})}

      ${author || photographer || publishedAt
			? `${validate_component(Stack, "Stack").$$render($$result, { stackSpace: creditsStackSpace }, {}, {
					default: () => `${author
					? `<p class="${"author font-weight:bold svelte-19qhu5i"}">${author}</p>`
					: ``}
          ${photographer
					? `<p class="${"photographer font-weight:bold svelte-19qhu5i"}">${photographer}</p>`
					: ``}

          ${publishedAt
					? `<time class="${"font-family:sans-serif font-size:small\n              text-transform:uppercase svelte-19qhu5i"}" itemprop="${"datePublished"}"${add_attribute("datetime", formatDate(publishedAt, "iso-string"), 0)}>${escape(formatDate(publishedAt, "day-month-year"))}</time>`
					: ``}`
				})}`
			: ``}`
		})}`
	})}</div>`;
});

/* node_modules/nature-immersive-svelte-components/src/components/Head/index.svelte generated by Svelte v3.38.3 */

const Head = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let imageURL;
	let { articleData } = $$props;
	let { articleURL, description, doi, immersiveURL, title, twitterHandle } = articleData;
	if ($$props.articleData === void 0 && $$bindings.articleData && articleData !== void 0) $$bindings.articleData(articleData);
	imageURL = `${immersiveURL}${doi}/img/${doi}.jpg`;
	return `${($$result.head += `<meta charset="${"UTF-8"}"><meta name="${"viewport"}" content="${"width=device-width, initial-scale=1.0, shrink-to-fit=no"}">${($$result.title = `<title>${escape(title)}</title>`, "")}<meta name="${"description"}"${add_attribute("content", description, 0)}><meta property="${"og:url"}"${add_attribute("content", `${articleURL}${doi}`, 0)}><meta property="${"og:type"}" content="${"article"}"><meta property="${"og:title"}"${add_attribute("content", title, 0)}><meta property="${"og:description"}"${add_attribute("content", description, 0)}><meta property="${"og:image"}"${add_attribute("content", imageURL, 0)}><meta name="${"twitter:card"}" content="${"summary_large_image"}"><meta name="${"twitter:site"}"${add_attribute("content", twitterHandle, 0)}><meta name="${"twitter:title"}"${add_attribute("content", title, 0)}><meta name="${"twitter:description"}"${add_attribute("content", description, 0)}><meta name="${"twitter:image"}"${add_attribute("content", imageURL, 0)}><link rel="${"apple-touch-icon"}" sizes="${"180x180"}" href="${"img/apple-touch-icon.png"}"><link rel="${"icon"}" type="${"image/png"}" sizes="${"32x32"}" href="${"img/favicon-32x32.png"}"><link rel="${"icon"}" type="${"image/png"}" sizes="${"16x16"}" href="${"img/favicon-16x16.png"}">`, "")}`;
});

/* node_modules/nature-immersive-svelte-components/src/components/LogoSpringerNature/index.svelte generated by Svelte v3.38.3 */

const css$e = {
	code: "svg.svelte-fftrry{display:block;overflow:visible}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  export let className = \\\"\\\";\\n  export let height = 1;\\n  export let title = \\\"Springer Nature\\\";\\n</script>\\n\\n<style>\\n  svg {\\n    display: block;\\n    overflow: visible;\\n  }\\n</style>\\n\\n<svg\\n  class=\\\"{className}\\\"\\n  height=\\\"{`${height}em`}\\\"\\n  viewBox=\\\"0 0 140 14\\\"\\n  focusable=\\\"false\\\"\\n  aria-hidden=\\\"true\\\"\\n>\\n  <path\\n    d=\\\"M74.9,5.7c0-2.8-2.4-3.8-4.6-3.8c-1.1,0-2.8,0-3.8,0v11.6h2.9V10h0.9c0.2,0,0.3,0,0.5,0l0,0l0,0c0.5,0.8,1.1,2,1.3,3.5\\n    c0.6,0,1.1,0,1.5,0h0.8c0.3,0,0.5,0,0.8,0c-0.3-1.8-1.2-3.5-1.8-4.4l0,0l0,0C74.3,8.2,74.9,7.1,74.9,5.7z\\n    M71.8,6.1\\n    c0,1.2-0.5,1.7-1.6,1.7c-0.4,0-0.6,0-0.8,0l0,0V4.1l0,0c0.3,0,0.6,0,0.9,0C71.6,4.1,71.8,4.9,71.8,6.1z\\n    M64.3,13.5v-2.3h-4.1V8.7\\n    h3.7V6.5h-3.7V4.2h4.1V1.9h-6.8v9.5c0,0,0,0.9,0.6,1.5c0.4,0.4,0.9,0.6,1.6,0.6C61.7,13.6,64,13.5,64.3,13.5z\\n    M51.4,13.9\\n    c1.1,0,2.8-0.3,4.1-0.9V7.2h-3.8v2h1.2v2.4l0,0c-0.3,0.1-1,0.2-1.3,0.2c-1.5,0-2.1-1.1-2.1-4c0-2.5,0.9-3.8,2.7-3.8\\n    c0.6,0,1.5,0.3,2.4,0.7l0.8-1.9c-1.1-0.7-2.4-1-3.6-1c-1.7,0-3,0.5-3.8,1.5c-0.8,1-1.2,2.5-1.2,4.5C46.6,12.2,47.9,13.9,51.4,13.9z\\n    M41.7,13.5h3V1.9h-2.5v7.6l-3.4-7.6h-3.1v11.6h2.5V6.2L41.7,13.5L41.7,13.5z\\n    M30.2,13.5h2.9V2h-2.9V13.5z M26.6,9.1L26.6,9.1\\n    L26.6,9.1c1-0.8,1.5-2,1.5-3.4c0-2.8-2.4-3.8-4.6-3.8c-1.1,0-2.8,0-3.8,0v11.6h2.9V10h0.9c0.2,0,0.3,0,0.5,0l0,0l0,0\\n    c0.5,0.8,1.1,2,1.3,3.5c0.6,0,1.1,0,1.5,0h0.8c0.3,0,0.5,0,0.8,0C28.1,11.7,27.2,10,26.6,9.1z\\n    M25,6.1c0,1.2-0.5,1.7-1.6,1.7\\n    c-0.4,0-0.6,0-0.8,0l0,0V4.1l0,0c0.3,0,0.6,0,0.9,0C24.8,4.1,25,4.9,25,6.1z\\n    M18.2,5.6c0-2.4-1.5-3.7-4.3-3.7c-1.1,0-2.8,0-3.8,0\\n    v11.6H13V10h0.9C15.2,10,18.2,9.6,18.2,5.6z\\n    M15.5,6.1c0,1.2-0.5,1.7-1.6,1.7c-0.4,0-0.6,0-0.8,0l0,0V4.1l0,0c0.3,0,0.6,0,0.9,0\\n    C15.2,4.1,15.5,4.9,15.5,6.1z\\n    M3.3,4.1c0-0.6,0.4-1.3,1.4-1.3c0.7,0,1.5,0.2,2.5,0.7l1-2.1C7,0.8,5.8,0.4,4.5,0.4\\n    c-2.6,0-4.2,1.4-4.2,3.8s1.8,3.3,3.3,4c1.1,0.5,2,1,2,1.8c0,0.7-0.7,1.2-1.6,1.2c-0.8,0-1.7-0.3-2.9-0.9l-1,2.2\\n    c1.4,0.8,2.7,1.1,4.1,1.1c2.7,0,4.3-1.5,4.3-4c0-2.4-1.8-3.2-3.3-3.9C4.2,5.3,3.3,4.9,3.3,4.1L3.3,4.1z\\n    M134.8,11.2V8.7h3.7V6.5\\n    h-3.7V4.2h4.1V1.9h-6.8v9.5c0,0,0,0.9,0.6,1.5c0.4,0.4,0.9,0.6,1.6,0.6c2.1,0,4.4-0.1,4.7-0.1v-2.3H134.8L134.8,11.2z\\n    M128.6,9.1\\n    L128.6,9.1L128.6,9.1c1-0.8,1.5-2,1.5-3.4c0-2.8-2.4-3.8-4.6-3.8c-1.1,0-2.8,0-3.8,0v11.6h2.9V10h0.9c0.2,0,0.3,0,0.5,0l0,0l0,0\\n    c0.5,0.8,1.1,2,1.3,3.5c0.6,0,1.1,0,1.5,0h0.8c0.3,0,0.5,0,0.8,0C130.1,11.7,129.2,10,128.6,9.1L128.6,9.1z\\n    M127,6.1\\n    c0,1.2-0.5,1.7-1.6,1.7c-0.4,0-0.6,0-0.8,0l0,0V4.1l0,0c0.3,0,0.6,0,0.9,0C126.8,4.1,127,4.9,127,6.1z\\n    M119.5,9.4V1.9h-3v7.7\\n    c0,1.2-0.1,1.9-1.4,1.9c-1.3,0-1.5-0.6-1.5-1.9V1.9h-3v7.8c0,2.8,1.3,4,4.3,4C118.1,13.8,119.5,12.4,119.5,9.4L119.5,9.4z\\n    M106.8,4.3h2.2V1.9h-7.8v2.4h2.6v9.2h3C106.8,13.5,106.8,4.3,106.8,4.3z\\n    M98,13.5h3.1L98.3,1.9h-4.5L91,13.5h2.9l0.4-1.8h3.2 L98,13.5L98,13.5z\\n    M97.2,9.5h-2.5l1.2-5H96l0,0L97.2,9.5L97.2,9.5z\\n    M85.9,13.5h3.4v-13h-2.8l0.1,9.1l-4.2-9.1h-3.4v13h2.7l0-9\\n    l0.1,0.2L85.9,13.5L85.9,13.5z\\\"\\n  ></path>\\n</svg>\\n<span class=\\\"visually-hidden\\\">{title}</span>\\n\"],\"names\":[],\"mappings\":\"AAOE,GAAG,cAAC,CAAC,AACH,OAAO,CAAE,KAAK,CACd,QAAQ,CAAE,OAAO,AACnB,CAAC\"}"
};

const LogoSpringerNature = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { className = "" } = $$props;
	let { height = 1 } = $$props;
	let { title = "Springer Nature" } = $$props;
	if ($$props.className === void 0 && $$bindings.className && className !== void 0) $$bindings.className(className);
	if ($$props.height === void 0 && $$bindings.height && height !== void 0) $$bindings.height(height);
	if ($$props.title === void 0 && $$bindings.title && title !== void 0) $$bindings.title(title);
	$$result.css.add(css$e);

	return `<svg class="${escape(null_to_empty(className)) + " svelte-fftrry"}"${add_attribute("height", `${height}em`, 0)} viewBox="${"0 0 140 14"}" focusable="${"false"}" aria-hidden="${"true"}"><path d="${"M74.9,5.7c0-2.8-2.4-3.8-4.6-3.8c-1.1,0-2.8,0-3.8,0v11.6h2.9V10h0.9c0.2,0,0.3,0,0.5,0l0,0l0,0c0.5,0.8,1.1,2,1.3,3.5\n    c0.6,0,1.1,0,1.5,0h0.8c0.3,0,0.5,0,0.8,0c-0.3-1.8-1.2-3.5-1.8-4.4l0,0l0,0C74.3,8.2,74.9,7.1,74.9,5.7z\n    M71.8,6.1\n    c0,1.2-0.5,1.7-1.6,1.7c-0.4,0-0.6,0-0.8,0l0,0V4.1l0,0c0.3,0,0.6,0,0.9,0C71.6,4.1,71.8,4.9,71.8,6.1z\n    M64.3,13.5v-2.3h-4.1V8.7\n    h3.7V6.5h-3.7V4.2h4.1V1.9h-6.8v9.5c0,0,0,0.9,0.6,1.5c0.4,0.4,0.9,0.6,1.6,0.6C61.7,13.6,64,13.5,64.3,13.5z\n    M51.4,13.9\n    c1.1,0,2.8-0.3,4.1-0.9V7.2h-3.8v2h1.2v2.4l0,0c-0.3,0.1-1,0.2-1.3,0.2c-1.5,0-2.1-1.1-2.1-4c0-2.5,0.9-3.8,2.7-3.8\n    c0.6,0,1.5,0.3,2.4,0.7l0.8-1.9c-1.1-0.7-2.4-1-3.6-1c-1.7,0-3,0.5-3.8,1.5c-0.8,1-1.2,2.5-1.2,4.5C46.6,12.2,47.9,13.9,51.4,13.9z\n    M41.7,13.5h3V1.9h-2.5v7.6l-3.4-7.6h-3.1v11.6h2.5V6.2L41.7,13.5L41.7,13.5z\n    M30.2,13.5h2.9V2h-2.9V13.5z M26.6,9.1L26.6,9.1\n    L26.6,9.1c1-0.8,1.5-2,1.5-3.4c0-2.8-2.4-3.8-4.6-3.8c-1.1,0-2.8,0-3.8,0v11.6h2.9V10h0.9c0.2,0,0.3,0,0.5,0l0,0l0,0\n    c0.5,0.8,1.1,2,1.3,3.5c0.6,0,1.1,0,1.5,0h0.8c0.3,0,0.5,0,0.8,0C28.1,11.7,27.2,10,26.6,9.1z\n    M25,6.1c0,1.2-0.5,1.7-1.6,1.7\n    c-0.4,0-0.6,0-0.8,0l0,0V4.1l0,0c0.3,0,0.6,0,0.9,0C24.8,4.1,25,4.9,25,6.1z\n    M18.2,5.6c0-2.4-1.5-3.7-4.3-3.7c-1.1,0-2.8,0-3.8,0\n    v11.6H13V10h0.9C15.2,10,18.2,9.6,18.2,5.6z\n    M15.5,6.1c0,1.2-0.5,1.7-1.6,1.7c-0.4,0-0.6,0-0.8,0l0,0V4.1l0,0c0.3,0,0.6,0,0.9,0\n    C15.2,4.1,15.5,4.9,15.5,6.1z\n    M3.3,4.1c0-0.6,0.4-1.3,1.4-1.3c0.7,0,1.5,0.2,2.5,0.7l1-2.1C7,0.8,5.8,0.4,4.5,0.4\n    c-2.6,0-4.2,1.4-4.2,3.8s1.8,3.3,3.3,4c1.1,0.5,2,1,2,1.8c0,0.7-0.7,1.2-1.6,1.2c-0.8,0-1.7-0.3-2.9-0.9l-1,2.2\n    c1.4,0.8,2.7,1.1,4.1,1.1c2.7,0,4.3-1.5,4.3-4c0-2.4-1.8-3.2-3.3-3.9C4.2,5.3,3.3,4.9,3.3,4.1L3.3,4.1z\n    M134.8,11.2V8.7h3.7V6.5\n    h-3.7V4.2h4.1V1.9h-6.8v9.5c0,0,0,0.9,0.6,1.5c0.4,0.4,0.9,0.6,1.6,0.6c2.1,0,4.4-0.1,4.7-0.1v-2.3H134.8L134.8,11.2z\n    M128.6,9.1\n    L128.6,9.1L128.6,9.1c1-0.8,1.5-2,1.5-3.4c0-2.8-2.4-3.8-4.6-3.8c-1.1,0-2.8,0-3.8,0v11.6h2.9V10h0.9c0.2,0,0.3,0,0.5,0l0,0l0,0\n    c0.5,0.8,1.1,2,1.3,3.5c0.6,0,1.1,0,1.5,0h0.8c0.3,0,0.5,0,0.8,0C130.1,11.7,129.2,10,128.6,9.1L128.6,9.1z\n    M127,6.1\n    c0,1.2-0.5,1.7-1.6,1.7c-0.4,0-0.6,0-0.8,0l0,0V4.1l0,0c0.3,0,0.6,0,0.9,0C126.8,4.1,127,4.9,127,6.1z\n    M119.5,9.4V1.9h-3v7.7\n    c0,1.2-0.1,1.9-1.4,1.9c-1.3,0-1.5-0.6-1.5-1.9V1.9h-3v7.8c0,2.8,1.3,4,4.3,4C118.1,13.8,119.5,12.4,119.5,9.4L119.5,9.4z\n    M106.8,4.3h2.2V1.9h-7.8v2.4h2.6v9.2h3C106.8,13.5,106.8,4.3,106.8,4.3z\n    M98,13.5h3.1L98.3,1.9h-4.5L91,13.5h2.9l0.4-1.8h3.2 L98,13.5L98,13.5z\n    M97.2,9.5h-2.5l1.2-5H96l0,0L97.2,9.5L97.2,9.5z\n    M85.9,13.5h3.4v-13h-2.8l0.1,9.1l-4.2-9.1h-3.4v13h2.7l0-9\n    l0.1,0.2L85.9,13.5L85.9,13.5z"}"></path></svg>
<span class="${"visually-hidden"}">${escape(title)}</span>`;
});

/* node_modules/nature-immersive-svelte-components/src/components/Footer/index.svelte generated by Svelte v3.38.3 */

const css$d = {
	code: ".footer.svelte-55fbus{align-items:flex-start}a.svelte-55fbus{color:var(--text-color-invert)}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  import { Box, Stack, ClusterList } from \\\"creditdesign-svelte-components\\\";\\n  import LogoSpringerNature from \\\"../LogoSpringerNature/index.svelte\\\";\\n</script>\\n\\n<style>\\n  .footer {\\n    align-items: flex-start;\\n  }\\n\\n  a {\\n    color: var(--text-color-invert);\\n  }\\n</style>\\n\\n<footer\\n  class=\\\"footer font-size:small font-family:sans-serif\\\"\\n  data-theme=\\\"invert\\\"\\n>\\n  <Box>\\n    <Stack stackSpace=\\\"var(--s-1)\\\">\\n      <div>\\n        <LogoSpringerNature height={1.5} />\\n      </div>\\n\\n      <ClusterList>\\n        <li>\\n          <a href=\\\"https://www.nature.com/info/privacy.html\\\">Privacy Policy</a>\\n        </li>\\n        <li>\\n          <a href=\\\"https://www.nature.com/info/cookies.html\\\">Use of cookies</a>\\n        </li>\\n        <li>\\n          <a href=\\\"https://www.nature.com/info/legal_notice.html\\\">\\n            Legal notice\\n          </a>\\n        </li>\\n        <li>\\n          <a href=\\\"https://www.nature.com/info/tandc.html\\\">\\n            Terms & Conditions\\n          </a>\\n        </li>\\n        <li>\\n          <a href=\\\"https://www.nature.com/info/accessibility_statement.html\\\">\\n            Accessibility statement\\n          </a>\\n        </li>\\n      </ClusterList>\\n\\n      <small>© 2021 Springer Nature Limited. All rights reserved.</small>\\n    </Stack>\\n  </Box>\\n</footer>\\n\"],\"names\":[],\"mappings\":\"AAME,OAAO,cAAC,CAAC,AACP,WAAW,CAAE,UAAU,AACzB,CAAC,AAED,CAAC,cAAC,CAAC,AACD,KAAK,CAAE,IAAI,mBAAmB,CAAC,AACjC,CAAC\"}"
};

const Footer = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$d);

	return `<footer class="${"footer font-size:small font-family:sans-serif svelte-55fbus"}" data-theme="${"invert"}">${validate_component(Box, "Box").$$render($$result, {}, {}, {
		default: () => `${validate_component(Stack, "Stack").$$render($$result, { stackSpace: "var(--s-1)" }, {}, {
			default: () => `<div>${validate_component(LogoSpringerNature, "LogoSpringerNature").$$render($$result, { height: 1.5 }, {}, {})}</div>

      ${validate_component(ClusterList, "ClusterList").$$render($$result, {}, {}, {
				default: () => `<li><a href="${"https://www.nature.com/info/privacy.html"}" class="${"svelte-55fbus"}">Privacy Policy</a></li>
        <li><a href="${"https://www.nature.com/info/cookies.html"}" class="${"svelte-55fbus"}">Use of cookies</a></li>
        <li><a href="${"https://www.nature.com/info/legal_notice.html"}" class="${"svelte-55fbus"}">Legal notice
          </a></li>
        <li><a href="${"https://www.nature.com/info/tandc.html"}" class="${"svelte-55fbus"}">Terms &amp; Conditions
          </a></li>
        <li><a href="${"https://www.nature.com/info/accessibility_statement.html"}" class="${"svelte-55fbus"}">Accessibility statement
          </a></li>`
			})}

      <small>© 2021 Springer Nature Limited. All rights reserved.</small>`
		})}`
	})}</footer>`;
});

const subscriber_queue = [];
/**
 * Creates a `Readable` store that allows reading by subscription.
 * @param value initial value
 * @param {StartStopNotifier}start start and stop notifications for subscriptions
 */
function readable(value, start) {
    return {
        subscribe: writable(value, start).subscribe
    };
}
/**
 * Create a `Writable` store that allows both updating and reading by subscription.
 * @param {*=}value initial value
 * @param {StartStopNotifier=}start start and stop notifications for subscriptions
 */
function writable(value, start = noop) {
    let stop;
    const subscribers = [];
    function set(new_value) {
        if (safe_not_equal(value, new_value)) {
            value = new_value;
            if (stop) { // store is ready
                const run_queue = !subscriber_queue.length;
                for (let i = 0; i < subscribers.length; i += 1) {
                    const s = subscribers[i];
                    s[1]();
                    subscriber_queue.push(s, value);
                }
                if (run_queue) {
                    for (let i = 0; i < subscriber_queue.length; i += 2) {
                        subscriber_queue[i][0](subscriber_queue[i + 1]);
                    }
                    subscriber_queue.length = 0;
                }
            }
        }
    }
    function update(fn) {
        set(fn(value));
    }
    function subscribe(run, invalidate = noop) {
        const subscriber = [run, invalidate];
        subscribers.push(subscriber);
        if (subscribers.length === 1) {
            stop = start(set) || noop;
        }
        run(value);
        return () => {
            const index = subscribers.indexOf(subscriber);
            if (index !== -1) {
                subscribers.splice(index, 1);
            }
            if (subscribers.length === 0) {
                stop();
                stop = null;
            }
        };
    }
    return { set, update, subscribe };
}
function derived(stores, fn, initial_value) {
    const single = !Array.isArray(stores);
    const stores_array = single
        ? [stores]
        : stores;
    const auto = fn.length < 2;
    return readable(initial_value, (set) => {
        let inited = false;
        const values = [];
        let pending = 0;
        let cleanup = noop;
        const sync = () => {
            if (pending) {
                return;
            }
            cleanup();
            const result = fn(single ? values[0] : values, set);
            if (auto) {
                set(result);
            }
            else {
                cleanup = is_function(result) ? result : noop;
            }
        };
        const unsubscribers = stores_array.map((store, i) => subscribe(store, (value) => {
            values[i] = value;
            pending &= ~(1 << i);
            if (inited) {
                sync();
            }
        }, () => {
            pending |= (1 << i);
        }));
        inited = true;
        sync();
        return function stop() {
            run_all(unsubscribers);
            cleanup();
        };
    });
}

/* eslint-disable consistent-return */

const menuElement = writable();

const menuHeight = derived(
  menuElement,
  ($menuElement, set) => {
    if (!$menuElement) return;

    const ro = new ResizeObserver(([entry]) => {
      let { offsetHeight } = entry.target;
      set(offsetHeight);
    });

    ro.observe($menuElement);

    return () => ro.disconnect();
  },
  0
);

/* node_modules/nature-immersive-svelte-components/src/components/MenuList/index.svelte generated by Svelte v3.38.3 */

const css$c = {
	code: "nav.svelte-dztoe{--switcher-min-width:var(--measure);--switcher-space:var(--s-1);--modifier:calc(\n      var(--switcher-min-width) - (100% - var(--switcher-space))\n    );position:absolute;top:calc(1.6em + var(--s-1) + var(--s-1));left:0;width:100vw;max-width:none;padding:var(--s-2);border-top:1px solid var(--text-color-invert)}@media(prefers-reduced-motion: reduce){nav.svelte-dztoe{animation-duration:1ms !important;animation-delay:0ms !important}}.menu-switcher.svelte-dztoe{overflow:hidden}ul.svelte-dztoe{display:flex;flex-wrap:wrap;justify-content:space-between;max-width:none;padding:0;margin:calc((var(--switcher-space) / 2) * -1);list-style:none}li.svelte-dztoe{flex-basis:calc(var(--modifier) * 999);min-width:fit-content;margin:calc(var(--switcher-space) / 2)}.flex-basis\\:100.svelte-dztoe{flex-basis:100%}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  import { slide } from \\\"svelte/transition\\\";\\n  import { quadIn, quadOut } from \\\"svelte/easing\\\";\\n\\n  export let menuLinks = [];\\n  export let lastMenuLinkElem = null;\\n  export let menuHeight = 0;\\n\\n  let style = `top: ${menuHeight}px;`;\\n</script>\\n\\n<style>\\n  nav {\\n    --switcher-min-width: var(--measure);\\n    --switcher-space: var(--s-1);\\n    --modifier: calc(\\n      var(--switcher-min-width) - (100% - var(--switcher-space))\\n    );\\n\\n    position: absolute;\\n    top: calc(1.6em + var(--s-1) + var(--s-1));\\n    left: 0;\\n    width: 100vw;\\n    max-width: none;\\n    padding: var(--s-2);\\n    border-top: 1px solid var(--text-color-invert);\\n  }\\n\\n  /* If prefers reduced motion is set, don't animate the\\n    triangle spinning */\\n  @media (prefers-reduced-motion: reduce) {\\n    nav {\\n      animation-duration: 1ms !important;\\n      animation-delay: 0ms !important;\\n    }\\n  }\\n\\n  .menu-switcher {\\n    overflow: hidden;\\n  }\\n\\n  ul {\\n    display: flex;\\n    flex-wrap: wrap;\\n    justify-content: space-between;\\n    max-width: none;\\n    padding: 0;\\n    margin: calc((var(--switcher-space) / 2) * -1);\\n    list-style: none;\\n  }\\n\\n  li {\\n    flex-basis: calc(var(--modifier) * 999);\\n    min-width: fit-content;\\n    margin: calc(var(--switcher-space) / 2);\\n  }\\n\\n  /* Used for the case where there are more than 8 list items\\n\\tso that the will be stacked automatically. Appiled with JS. */\\n  .flex-basis\\\\:100 {\\n    flex-basis: 100%;\\n  }\\n</style>\\n\\n<nav\\n  data-theme=\\\"menu\\\"\\n  {style}\\n  in:slide={{ duration: 250, easing: quadOut }}\\n  out:slide={{ duration: 250, easing: quadIn }}\\n  class=\\\"font-family:sans-serif\\\"\\n>\\n  <div class=\\\"menu-switcher\\\">\\n    <ul>\\n      {#each menuLinks as { text, href }, i}\\n        {#if i !== menuLinks.length - 1}\\n          <li class:flex-basis:100={menuLinks.length > 8}>\\n            <a\\n              {href}\\n              on:focus\\n              on:blur\\n              data-event-category=\\\"menu\\\"\\n              data-event-action=\\\"click\\\"\\n              data-event-label={text}\\n              class=\\\"text-decoration:none\\\"\\n            >\\n              {@html text}\\n            </a>\\n          </li>\\n        {:else}\\n          <li class:flex-basis:100={menuLinks.length > 8}>\\n            <a\\n              {href}\\n              on:focus\\n              on:blur\\n              bind:this={lastMenuLinkElem}\\n              data-event-category=\\\"menu\\\"\\n              data-event-action=\\\"click\\\"\\n              data-event-label={text}\\n              class=\\\"text-decoration:none\\\"\\n            >\\n              {@html text}\\n            </a>\\n          </li>\\n        {/if}\\n      {/each}\\n    </ul>\\n  </div>\\n</nav>\\n\"],\"names\":[],\"mappings\":\"AAYE,GAAG,aAAC,CAAC,AACH,oBAAoB,CAAE,cAAc,CACpC,gBAAgB,CAAE,UAAU,CAC5B,UAAU,CAAE;;KAEX,CAED,QAAQ,CAAE,QAAQ,CAClB,GAAG,CAAE,KAAK,KAAK,CAAC,CAAC,CAAC,IAAI,KAAK,CAAC,CAAC,CAAC,CAAC,IAAI,KAAK,CAAC,CAAC,CAC1C,IAAI,CAAE,CAAC,CACP,KAAK,CAAE,KAAK,CACZ,SAAS,CAAE,IAAI,CACf,OAAO,CAAE,IAAI,KAAK,CAAC,CACnB,UAAU,CAAE,GAAG,CAAC,KAAK,CAAC,IAAI,mBAAmB,CAAC,AAChD,CAAC,AAID,MAAM,AAAC,yBAAyB,MAAM,CAAC,AAAC,CAAC,AACvC,GAAG,aAAC,CAAC,AACH,kBAAkB,CAAE,GAAG,CAAC,UAAU,CAClC,eAAe,CAAE,GAAG,CAAC,UAAU,AACjC,CAAC,AACH,CAAC,AAED,cAAc,aAAC,CAAC,AACd,QAAQ,CAAE,MAAM,AAClB,CAAC,AAED,EAAE,aAAC,CAAC,AACF,OAAO,CAAE,IAAI,CACb,SAAS,CAAE,IAAI,CACf,eAAe,CAAE,aAAa,CAC9B,SAAS,CAAE,IAAI,CACf,OAAO,CAAE,CAAC,CACV,MAAM,CAAE,KAAK,CAAC,IAAI,gBAAgB,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,EAAE,CAAC,CAC9C,UAAU,CAAE,IAAI,AAClB,CAAC,AAED,EAAE,aAAC,CAAC,AACF,UAAU,CAAE,KAAK,IAAI,UAAU,CAAC,CAAC,CAAC,CAAC,GAAG,CAAC,CACvC,SAAS,CAAE,WAAW,CACtB,MAAM,CAAE,KAAK,IAAI,gBAAgB,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,AACzC,CAAC,AAID,gBAAgB,aAAC,CAAC,AAChB,UAAU,CAAE,IAAI,AAClB,CAAC\"}"
};

const MenuList = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { menuLinks = [] } = $$props;
	let { lastMenuLinkElem = null } = $$props;
	let { menuHeight = 0 } = $$props;
	let style = `top: ${menuHeight}px;`;
	if ($$props.menuLinks === void 0 && $$bindings.menuLinks && menuLinks !== void 0) $$bindings.menuLinks(menuLinks);
	if ($$props.lastMenuLinkElem === void 0 && $$bindings.lastMenuLinkElem && lastMenuLinkElem !== void 0) $$bindings.lastMenuLinkElem(lastMenuLinkElem);
	if ($$props.menuHeight === void 0 && $$bindings.menuHeight && menuHeight !== void 0) $$bindings.menuHeight(menuHeight);
	$$result.css.add(css$c);

	return `<nav data-theme="${"menu"}"${add_attribute("style", style, 0)} class="${"font-family:sans-serif svelte-dztoe"}"><div class="${"menu-switcher svelte-dztoe"}"><ul class="${"svelte-dztoe"}">${each(menuLinks, ({ text, href }, i) => `${i !== menuLinks.length - 1
	? `<li class="${["svelte-dztoe", menuLinks.length > 8 ? "flex-basis:100" : ""].join(" ").trim()}"><a${add_attribute("href", href, 0)} data-event-category="${"menu"}" data-event-action="${"click"}"${add_attribute("data-event-label", text, 0)} class="${"text-decoration:none"}">${text}</a>
          </li>`
	: `<li class="${["svelte-dztoe", menuLinks.length > 8 ? "flex-basis:100" : ""].join(" ").trim()}"><a${add_attribute("href", href, 0)} data-event-category="${"menu"}" data-event-action="${"click"}"${add_attribute("data-event-label", text, 0)} class="${"text-decoration:none"}"${add_attribute("this", lastMenuLinkElem, 1)}>${text}</a>
          </li>`}`)}</ul></div></nav>`;
});

/* node_modules/nature-immersive-svelte-components/src/components/MenuListStatic/index.svelte generated by Svelte v3.38.3 */

const css$b = {
	code: "nav.svelte-1fnr10s{left:0;width:100%;max-width:none;padding:var(--s-1)}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  import { Stack } from \\\"creditdesign-svelte-components\\\";\\n\\n  export let menuLinks;\\n</script>\\n\\n<style>\\n  nav {\\n    left: 0;\\n    width: 100%;\\n    max-width: none;\\n    padding: var(--s-1);\\n  }\\n</style>\\n\\n{#if menuLinks && menuLinks.length}\\n  <nav data-theme=\\\"menu\\\" class=\\\"font-family:sans-serif\\\">\\n    <Stack>\\n      <h2 id=\\\"menu\\\" class=\\\"font-size:base\\\" tabindex=\\\"-1\\\">Menu</h2>\\n      <ul>\\n        {#each menuLinks as { text, href }, i}\\n          <li>\\n            <a class=\\\"text-decoration:none\\\" {href}>\\n              {@html text}\\n            </a>\\n          </li>\\n        {/each}\\n      </ul>\\n    </Stack>\\n  </nav>\\n{/if}\\n\"],\"names\":[],\"mappings\":\"AAOE,GAAG,eAAC,CAAC,AACH,IAAI,CAAE,CAAC,CACP,KAAK,CAAE,IAAI,CACX,SAAS,CAAE,IAAI,CACf,OAAO,CAAE,IAAI,KAAK,CAAC,AACrB,CAAC\"}"
};

const MenuListStatic = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { menuLinks } = $$props;
	if ($$props.menuLinks === void 0 && $$bindings.menuLinks && menuLinks !== void 0) $$bindings.menuLinks(menuLinks);
	$$result.css.add(css$b);

	return `${menuLinks && menuLinks.length
	? `<nav data-theme="${"menu"}" class="${"font-family:sans-serif svelte-1fnr10s"}">${validate_component(Stack, "Stack").$$render($$result, {}, {}, {
			default: () => `<h2 id="${"menu"}" class="${"font-size:base"}" tabindex="${"-1"}">Menu</h2>
      <ul>${each(menuLinks, ({ text, href }, i) => `<li><a class="${"text-decoration:none"}"${add_attribute("href", href, 0)}>${text}</a>
          </li>`)}</ul>`
		})}</nav>`
	: ``}`;
});

/* node_modules/nature-immersive-svelte-components/src/components/LogoFacebook/index.svelte generated by Svelte v3.38.3 */

const css$a = {
	code: "svg.svelte-fftrry{display:block;overflow:visible}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  export let className = \\\"\\\";\\n  export let height = 1;\\n  export let title = \\\"Facebook\\\";\\n</script>\\n\\n<style>\\n  svg {\\n    display: block;\\n    overflow: visible;\\n  }\\n</style>\\n\\n<svg\\n  class=\\\"{className}\\\"\\n  height=\\\"{`${height}em`}\\\"\\n  viewBox=\\\"0 0 30 30\\\"\\n  focusable=\\\"false\\\"\\n  aria-hidden=\\\"true\\\"\\n>\\n  <path\\n    d=\\\"M30,15A15,15,0,1,1,15,0,15,15,0,0,1,30,15ZM15,2A13,13,0,1,0,28,15,13,13,0,0,0,15,2Z\\\"\\n  ></path>\\n  <path\\n    d=\\\"M15.89625,22.8625 L12.57125,22.8625 L12.57125,15.02125 L10.90875,15.02125\\n    L10.90875,12.31875 L12.57125,12.31875 L12.57125,10.69625 C12.57125,8.4925\\n    13.50875,7.18 16.175,7.18 L18.39375,7.18 L18.39375,9.8825 L17.00625,9.8825\\n    C15.96875,9.8825 15.9,10.26 15.9,10.965 L15.895,12.3175 L18.4075,12.3175\\n    L18.115,15.02 L15.89625,15.02 L15.89625,22.8625 Z\\\"\\n  ></path>\\n</svg>\\n<span class=\\\"visually-hidden\\\">{title}</span>\\n\"],\"names\":[],\"mappings\":\"AAOE,GAAG,cAAC,CAAC,AACH,OAAO,CAAE,KAAK,CACd,QAAQ,CAAE,OAAO,AACnB,CAAC\"}"
};

const LogoFacebook = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { className = "" } = $$props;
	let { height = 1 } = $$props;
	let { title = "Facebook" } = $$props;
	if ($$props.className === void 0 && $$bindings.className && className !== void 0) $$bindings.className(className);
	if ($$props.height === void 0 && $$bindings.height && height !== void 0) $$bindings.height(height);
	if ($$props.title === void 0 && $$bindings.title && title !== void 0) $$bindings.title(title);
	$$result.css.add(css$a);

	return `<svg class="${escape(null_to_empty(className)) + " svelte-fftrry"}"${add_attribute("height", `${height}em`, 0)} viewBox="${"0 0 30 30"}" focusable="${"false"}" aria-hidden="${"true"}"><path d="${"M30,15A15,15,0,1,1,15,0,15,15,0,0,1,30,15ZM15,2A13,13,0,1,0,28,15,13,13,0,0,0,15,2Z"}"></path><path d="${"M15.89625,22.8625 L12.57125,22.8625 L12.57125,15.02125 L10.90875,15.02125\n    L10.90875,12.31875 L12.57125,12.31875 L12.57125,10.69625 C12.57125,8.4925\n    13.50875,7.18 16.175,7.18 L18.39375,7.18 L18.39375,9.8825 L17.00625,9.8825\n    C15.96875,9.8825 15.9,10.26 15.9,10.965 L15.895,12.3175 L18.4075,12.3175\n    L18.115,15.02 L15.89625,15.02 L15.89625,22.8625 Z"}"></path></svg>
<span class="${"visually-hidden"}">${escape(title)}</span>`;
});

/* node_modules/nature-immersive-svelte-components/src/components/LogoTwitter/index.svelte generated by Svelte v3.38.3 */

const css$9 = {
	code: "svg.svelte-fftrry{display:block;overflow:visible}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  export let className = \\\"\\\";\\n  export let height = 1;\\n  export let title = \\\"Twitter\\\";\\n</script>\\n\\n<style>\\n  svg {\\n    display: block;\\n    overflow: visible;\\n  }\\n</style>\\n\\n<svg\\n  class=\\\"{className}\\\"\\n  height=\\\"{`${height}em`}\\\"\\n  viewBox=\\\"0 0 30 30\\\"\\n  focusable=\\\"false\\\"\\n  aria-hidden=\\\"true\\\"\\n>\\n  <path\\n    d=\\\"M30,15A15,15,0,1,1,15,0,15,15,0,0,1,30,15ZM15,2A13,13,0,1,0,28,15,13,13,0,0,0,15,2Z\\\"\\n  ></path>\\n  <path\\n    d=\\\"M20.8125,11.4875 C21.42,11.10375 21.8875,10.49625 22.105,9.7725\\n    C21.5375,10.1275 20.90875,10.385 20.23875,10.5225 C19.70625,9.9225\\n    18.9425,9.545 18.0975,9.545 C16.475,9.545 15.16,10.9325 15.16,12.6425\\n    C15.16,12.885 15.185,13.1225 15.235,13.3475 C12.7975,13.2175 10.63125,11.985\\n    9.1825,10.11 C8.93,10.56875 8.785,11.10125 8.785,11.66875 C8.785,12.74375\\n    9.30375,13.69125 10.09125,14.2475 C9.61125,14.23125 9.1575,14.09\\n    8.76125,13.86 L8.76125,13.8975 C8.76125,15.3975 9.77375,16.65125\\n    11.11875,16.935 C10.87125,17.0075 10.6125,17.04375 10.34375,17.04375\\n    C10.15625,17.04375 9.96875,17.025 9.79125,16.98875 C10.16625,18.22125\\n    11.24875,19.11875 12.535,19.1425 C11.52875,19.97375 10.2625,20.4675\\n    8.885,20.4675 C8.6475,20.4675 8.415,20.455 8.185,20.42625 C9.485,21.30375\\n    11.02875,21.81625 12.6875,21.81625 C18.09,21.81625 21.04375,17.095\\n    21.04375,13.00125 L21.03625,12.60125 C21.61125,12.16375 22.11125,11.6175\\n    22.50125,10.99625 C21.97375,11.2425 21.4075,11.40875 20.81375,11.48375\\n    L20.8125,11.4875 Z\\\"\\n  ></path>\\n</svg>\\n<span class=\\\"visually-hidden\\\">{title}</span>\\n\"],\"names\":[],\"mappings\":\"AAOE,GAAG,cAAC,CAAC,AACH,OAAO,CAAE,KAAK,CACd,QAAQ,CAAE,OAAO,AACnB,CAAC\"}"
};

const LogoTwitter = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { className = "" } = $$props;
	let { height = 1 } = $$props;
	let { title = "Twitter" } = $$props;
	if ($$props.className === void 0 && $$bindings.className && className !== void 0) $$bindings.className(className);
	if ($$props.height === void 0 && $$bindings.height && height !== void 0) $$bindings.height(height);
	if ($$props.title === void 0 && $$bindings.title && title !== void 0) $$bindings.title(title);
	$$result.css.add(css$9);

	return `<svg class="${escape(null_to_empty(className)) + " svelte-fftrry"}"${add_attribute("height", `${height}em`, 0)} viewBox="${"0 0 30 30"}" focusable="${"false"}" aria-hidden="${"true"}"><path d="${"M30,15A15,15,0,1,1,15,0,15,15,0,0,1,30,15ZM15,2A13,13,0,1,0,28,15,13,13,0,0,0,15,2Z"}"></path><path d="${"M20.8125,11.4875 C21.42,11.10375 21.8875,10.49625 22.105,9.7725\n    C21.5375,10.1275 20.90875,10.385 20.23875,10.5225 C19.70625,9.9225\n    18.9425,9.545 18.0975,9.545 C16.475,9.545 15.16,10.9325 15.16,12.6425\n    C15.16,12.885 15.185,13.1225 15.235,13.3475 C12.7975,13.2175 10.63125,11.985\n    9.1825,10.11 C8.93,10.56875 8.785,11.10125 8.785,11.66875 C8.785,12.74375\n    9.30375,13.69125 10.09125,14.2475 C9.61125,14.23125 9.1575,14.09\n    8.76125,13.86 L8.76125,13.8975 C8.76125,15.3975 9.77375,16.65125\n    11.11875,16.935 C10.87125,17.0075 10.6125,17.04375 10.34375,17.04375\n    C10.15625,17.04375 9.96875,17.025 9.79125,16.98875 C10.16625,18.22125\n    11.24875,19.11875 12.535,19.1425 C11.52875,19.97375 10.2625,20.4675\n    8.885,20.4675 C8.6475,20.4675 8.415,20.455 8.185,20.42625 C9.485,21.30375\n    11.02875,21.81625 12.6875,21.81625 C18.09,21.81625 21.04375,17.095\n    21.04375,13.00125 L21.03625,12.60125 C21.61125,12.16375 22.11125,11.6175\n    22.50125,10.99625 C21.97375,11.2425 21.4075,11.40875 20.81375,11.48375\n    L20.8125,11.4875 Z"}"></path></svg>
<span class="${"visually-hidden"}">${escape(title)}</span>`;
});

/* node_modules/nature-immersive-svelte-components/src/components/LogoEmail/index.svelte generated by Svelte v3.38.3 */

const css$8 = {
	code: "svg.svelte-fftrry{display:block;overflow:visible}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  export let className = \\\"\\\";\\n  export let height = 1;\\n  export let title = \\\"Email\\\";\\n</script>\\n\\n<style>\\n  svg {\\n    display: block;\\n    overflow: visible;\\n  }\\n</style>\\n\\n<svg\\n  class=\\\"{className}\\\"\\n  height=\\\"{`${height}em`}\\\"\\n  viewBox=\\\"0 0 30 30\\\"\\n  focusable=\\\"false\\\"\\n  aria-hidden=\\\"true\\\"\\n>\\n  <path\\n    d=\\\"M30,15A15,15,0,1,1,15,0,15,15,0,0,1,30,15ZM15,2A13,13,0,1,0,28,15,13,13,0,0,0,15,2Z\\\"\\n  ></path>\\n  <path\\n    d=\\\"M15,15.3269887 L10.6248577,11.9177869 C10.4236021,11.7609644\\n    10.1299323,11.7927468 9.96892789,11.988775 C9.80792343,12.1848031\\n    9.84055341,12.4708451 10.041809,12.6276676 L14.7012493,16.2584003\\n    C14.8680779,16.3940555 15.1152493,16.4013884 15.2915244,16.2640313\\n    C15.2939898,16.2622325 15.2963784,16.2603294 15.2987507,16.2584003\\n    L19.958191,12.6276676 C20.1594466,12.4708451 20.1920766,12.1848031\\n    20.0310721,11.988775 C19.8700677,11.7927468 19.5763979,11.7609644\\n    19.3751423,11.9177869 L15,15.3269887 Z M9,10 L21,10 C21.5522847,10\\n    22,10.4477153 22,11 L22,19 C22,19.5522847 21.5522847,20 21,20 L9,20\\n    C8.44771525,20 8,19.5522847 8,19 L8,11 C8,10.4477153 8.44771525,10 9,10 Z\\\"\\n  ></path>\\n</svg>\\n<span class=\\\"visually-hidden\\\">{title}</span>\\n\"],\"names\":[],\"mappings\":\"AAOE,GAAG,cAAC,CAAC,AACH,OAAO,CAAE,KAAK,CACd,QAAQ,CAAE,OAAO,AACnB,CAAC\"}"
};

const LogoEmail = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { className = "" } = $$props;
	let { height = 1 } = $$props;
	let { title = "Email" } = $$props;
	if ($$props.className === void 0 && $$bindings.className && className !== void 0) $$bindings.className(className);
	if ($$props.height === void 0 && $$bindings.height && height !== void 0) $$bindings.height(height);
	if ($$props.title === void 0 && $$bindings.title && title !== void 0) $$bindings.title(title);
	$$result.css.add(css$8);

	return `<svg class="${escape(null_to_empty(className)) + " svelte-fftrry"}"${add_attribute("height", `${height}em`, 0)} viewBox="${"0 0 30 30"}" focusable="${"false"}" aria-hidden="${"true"}"><path d="${"M30,15A15,15,0,1,1,15,0,15,15,0,0,1,30,15ZM15,2A13,13,0,1,0,28,15,13,13,0,0,0,15,2Z"}"></path><path d="${"M15,15.3269887 L10.6248577,11.9177869 C10.4236021,11.7609644\n    10.1299323,11.7927468 9.96892789,11.988775 C9.80792343,12.1848031\n    9.84055341,12.4708451 10.041809,12.6276676 L14.7012493,16.2584003\n    C14.8680779,16.3940555 15.1152493,16.4013884 15.2915244,16.2640313\n    C15.2939898,16.2622325 15.2963784,16.2603294 15.2987507,16.2584003\n    L19.958191,12.6276676 C20.1594466,12.4708451 20.1920766,12.1848031\n    20.0310721,11.988775 C19.8700677,11.7927468 19.5763979,11.7609644\n    19.3751423,11.9177869 L15,15.3269887 Z M9,10 L21,10 C21.5522847,10\n    22,10.4477153 22,11 L22,19 C22,19.5522847 21.5522847,20 21,20 L9,20\n    C8.44771525,20 8,19.5522847 8,19 L8,11 C8,10.4477153 8.44771525,10 9,10 Z"}"></path></svg>
<span class="${"visually-hidden"}">${escape(title)}</span>`;
});

const generateSocialURLs = (doi, articleURL, title, description) => {
  const facebookBaseURL = "https://www.facebook.com/sharer/sharer.php?u=";
  const twitterBaseURL = "https://twitter.com/intent/tweet?text=";
  const emailBaseURL = "mailto:?";

  const pdfURL = `public/pdf/${doi}.pdf`;

  const altPdfURL = `public/pdf/${doi}-alt.pdf`;

  const facebookCustom = `${articleURL}${doi}`;
  const facebookWebEncoded = encodeURIComponent(facebookCustom);
  const facebookURL = `${facebookBaseURL}${facebookWebEncoded}`;

  const twitterCustom = `${title}. ${description} ${articleURL}${doi}`;
  const twitterWebEncoded = encodeURIComponent(twitterCustom);
  const twitterURL = `${twitterBaseURL}${twitterWebEncoded}`;

  const emailCustom = `subject=${title}&body=${description} ${encodeURIComponent(
    articleURL
  )}${doi}`;
  const emailURL = `${emailBaseURL}${emailCustom}`;

  return {
    pdfURL,
    altPdfURL,
    facebookURL,
    twitterURL,
    emailURL,
  };
};

/* node_modules/nature-immersive-svelte-components/src/components/MenuSocialLinks/index.svelte generated by Svelte v3.38.3 */

const css$7 = {
	code: "a.svelte-1jvspx4{display:block}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  import { ClusterList } from \\\"creditdesign-svelte-components\\\";\\n  import LogoFacebook from \\\"../LogoFacebook/index.svelte\\\";\\n  import LogoTwitter from \\\"../LogoTwitter/index.svelte\\\";\\n  import LogoEmail from \\\"../LogoEmail/index.svelte\\\";\\n\\n  export let articleData;\\n  export let logoHeight = 1.6;\\n\\n  import generateSocialURLs from \\\"../utils/generate-social-urls.js\\\";\\n\\n  let { doi, articleURL, title, description } = articleData;\\n\\n  let { facebookURL, twitterURL, emailURL } = generateSocialURLs(\\n    doi,\\n    articleURL,\\n    title,\\n    description\\n  );\\n</script>\\n\\n<style>\\n  a {\\n    display: block;\\n  }\\n</style>\\n\\n<h2 class=\\\"visually-hidden\\\">Sharing links</h2>\\n<ClusterList clusterSpace=\\\"var(--s-2)\\\">\\n  <li>\\n    <a href={twitterURL}>\\n      <LogoTwitter height={logoHeight} />\\n    </a>\\n  </li>\\n\\n  <li>\\n    <a href={facebookURL}>\\n      <LogoFacebook height={logoHeight} />\\n    </a>\\n  </li>\\n\\n  <li>\\n    <a href={emailURL}>\\n      <LogoEmail height={logoHeight} />\\n    </a>\\n  </li>\\n</ClusterList>\\n\"],\"names\":[],\"mappings\":\"AAsBE,CAAC,eAAC,CAAC,AACD,OAAO,CAAE,KAAK,AAChB,CAAC\"}"
};

const MenuSocialLinks = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { articleData } = $$props;
	let { logoHeight = 1.6 } = $$props;
	let { doi, articleURL, title, description } = articleData;
	let { facebookURL, twitterURL, emailURL } = generateSocialURLs(doi, articleURL, title, description);
	if ($$props.articleData === void 0 && $$bindings.articleData && articleData !== void 0) $$bindings.articleData(articleData);
	if ($$props.logoHeight === void 0 && $$bindings.logoHeight && logoHeight !== void 0) $$bindings.logoHeight(logoHeight);
	$$result.css.add(css$7);

	return `<h2 class="${"visually-hidden"}">Sharing links</h2>
${validate_component(ClusterList, "ClusterList").$$render($$result, { clusterSpace: "var(--s-2)" }, {}, {
		default: () => `<li><a${add_attribute("href", twitterURL, 0)} class="${"svelte-1jvspx4"}">${validate_component(LogoTwitter, "LogoTwitter").$$render($$result, { height: logoHeight }, {}, {})}</a></li>

  <li><a${add_attribute("href", facebookURL, 0)} class="${"svelte-1jvspx4"}">${validate_component(LogoFacebook, "LogoFacebook").$$render($$result, { height: logoHeight }, {}, {})}</a></li>

  <li><a${add_attribute("href", emailURL, 0)} class="${"svelte-1jvspx4"}">${validate_component(LogoEmail, "LogoEmail").$$render($$result, { height: logoHeight }, {}, {})}</a></li>`
	})}`;
});

/* node_modules/nature-immersive-svelte-components/src/components/LogoChevron/index.svelte generated by Svelte v3.38.3 */

const css$6 = {
	code: "svg.svelte-fftrry{display:block;overflow:visible}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  export let className = \\\"\\\";\\n  export let height = 1;\\n</script>\\n\\n<style>\\n  svg {\\n    display: block;\\n    overflow: visible;\\n  }\\n</style>\\n\\n<svg\\n  class=\\\"{className}\\\"\\n  height=\\\"{`${height}em`}\\\"\\n  viewBox=\\\"0 0 40 24\\\"\\n  focusable=\\\"false\\\"\\n  aria-hidden=\\\"true\\\"\\n>\\n  <path\\n    d=\\\"M20,14.3L6.8,1.2c-1.6-1.6-4.1-1.6-5.7,0s-1.6,4.1,0,5.7l16,16c1.6,1.6,4.1,1.6,5.7,0l16-16c1.6-1.6,1.6-4.1,0-5.7\\n    s-4.1-1.6-5.7,0L20,14.3z\\\"\\n  ></path>\\n</svg>\\n\"],\"names\":[],\"mappings\":\"AAME,GAAG,cAAC,CAAC,AACH,OAAO,CAAE,KAAK,CACd,QAAQ,CAAE,OAAO,AACnB,CAAC\"}"
};

const LogoChevron = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { className = "" } = $$props;
	let { height = 1 } = $$props;
	if ($$props.className === void 0 && $$bindings.className && className !== void 0) $$bindings.className(className);
	if ($$props.height === void 0 && $$bindings.height && height !== void 0) $$bindings.height(height);
	$$result.css.add(css$6);
	return `<svg class="${escape(null_to_empty(className)) + " svelte-fftrry"}"${add_attribute("height", `${height}em`, 0)} viewBox="${"0 0 40 24"}" focusable="${"false"}" aria-hidden="${"true"}"><path d="${"M20,14.3L6.8,1.2c-1.6-1.6-4.1-1.6-5.7,0s-1.6,4.1,0,5.7l16,16c1.6,1.6,4.1,1.6,5.7,0l16-16c1.6-1.6,1.6-4.1,0-5.7\n    s-4.1-1.6-5.7,0L20,14.3z"}"></path></svg>`;
});

/* node_modules/nature-immersive-svelte-components/src/components/ExpandButton/index.svelte generated by Svelte v3.38.3 */

const css$5 = {
	code: "button.svelte-1b75wvq.svelte-1b75wvq{display:flex;gap:var(--s-2);align-items:center;height:1.8em;padding:0 var(--s-1);font-size:inherit;border-style:solid;border-width:1px}.toggle-icon.svelte-1b75wvq.svelte-1b75wvq{transition:transform 250ms ease;transform:rotate(0deg)}@media(prefers-reduced-motion: reduce){.toggle-icon.svelte-1b75wvq.svelte-1b75wvq{transition:none}}button[aria-expanded=\"true\"].svelte-1b75wvq .toggle-icon.svelte-1b75wvq{transform:rotate(180deg)}.no-flexbox-gap .expand-button > * + *{margin-left:var(--s-2)}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  import LogoChevron from \\\"../LogoChevron/index.svelte\\\";\\n\\n  export let className = \\\"\\\";\\n  export let expanded = false;\\n  /**\\n   * Text that will be displayed in the button when it is expanded\\n   */\\n  export let expandedMessage = \\\"Close\\\";\\n  /**\\n   * Text that will be displayed in the button when it is not expanded\\n   */\\n  export let message = \\\"Open\\\";\\n  export let theme = \\\"\\\";\\n\\n  let buttonElement;\\n\\n  /**\\n   * Exported function so that the button element can be\\n   * focused programatically by the parent component.\\n   * Ref: https://stackoverflow.com/a/58288696\\n   */\\n  export function focusButton() {\\n    buttonElement.focus();\\n  }\\n</script>\\n\\n<style>\\n  button {\\n    display: flex;\\n    gap: var(--s-2);\\n    align-items: center;\\n    height: 1.8em;\\n    padding: 0 var(--s-1);\\n    font-size: inherit;\\n    border-style: solid;\\n    border-width: 1px;\\n  }\\n\\n  .toggle-icon {\\n    transition: transform 250ms ease;\\n    transform: rotate(0deg);\\n  }\\n\\n  /* If prefers reduced motion is set, don't animate the\\n    triangle spinning */\\n  @media (prefers-reduced-motion: reduce) {\\n    .toggle-icon {\\n      transition: none;\\n    }\\n  }\\n\\n  button[aria-expanded=\\\"true\\\"] .toggle-icon {\\n    transform: rotate(180deg);\\n  }\\n\\n  :global(.no-flexbox-gap .expand-button > * + *) {\\n    margin-left: var(--s-2);\\n  }\\n</style>\\n\\n<button\\n  aria-expanded={expanded}\\n  bind:this={buttonElement}\\n  class={`expand-button ${className}`}\\n  data-event-action=\\\"click\\\"\\n  data-event-category={message}\\n  data-event-label=\\\"Expand button clicked\\\"\\n  data-theme={theme}\\n  data-track=\\\"click\\\"\\n  on:blur\\n  on:click\\n  on:focus\\n  type=\\\"button\\\"\\n>\\n  <span>\\n    {#if expanded}{expandedMessage}{:else}{message}{/if}</span\\n  >\\n  <span class=\\\"toggle-icon\\\">\\n    <LogoChevron height=\\\"0.3\\\" />\\n  </span>\\n</button>\\n\"],\"names\":[],\"mappings\":\"AA4BE,MAAM,8BAAC,CAAC,AACN,OAAO,CAAE,IAAI,CACb,GAAG,CAAE,IAAI,KAAK,CAAC,CACf,WAAW,CAAE,MAAM,CACnB,MAAM,CAAE,KAAK,CACb,OAAO,CAAE,CAAC,CAAC,IAAI,KAAK,CAAC,CACrB,SAAS,CAAE,OAAO,CAClB,YAAY,CAAE,KAAK,CACnB,YAAY,CAAE,GAAG,AACnB,CAAC,AAED,YAAY,8BAAC,CAAC,AACZ,UAAU,CAAE,SAAS,CAAC,KAAK,CAAC,IAAI,CAChC,SAAS,CAAE,OAAO,IAAI,CAAC,AACzB,CAAC,AAID,MAAM,AAAC,yBAAyB,MAAM,CAAC,AAAC,CAAC,AACvC,YAAY,8BAAC,CAAC,AACZ,UAAU,CAAE,IAAI,AAClB,CAAC,AACH,CAAC,AAED,MAAM,CAAC,aAAa,CAAC,MAAM,gBAAC,CAAC,YAAY,eAAC,CAAC,AACzC,SAAS,CAAE,OAAO,MAAM,CAAC,AAC3B,CAAC,AAEO,sCAAsC,AAAE,CAAC,AAC/C,WAAW,CAAE,IAAI,KAAK,CAAC,AACzB,CAAC\"}"
};

const ExpandButton = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { className = "" } = $$props;
	let { expanded = false } = $$props;
	let { expandedMessage = "Close" } = $$props;
	let { message = "Open" } = $$props;
	let { theme = "" } = $$props;
	let buttonElement;

	function focusButton() {
		buttonElement.focus();
	}

	if ($$props.className === void 0 && $$bindings.className && className !== void 0) $$bindings.className(className);
	if ($$props.expanded === void 0 && $$bindings.expanded && expanded !== void 0) $$bindings.expanded(expanded);
	if ($$props.expandedMessage === void 0 && $$bindings.expandedMessage && expandedMessage !== void 0) $$bindings.expandedMessage(expandedMessage);
	if ($$props.message === void 0 && $$bindings.message && message !== void 0) $$bindings.message(message);
	if ($$props.theme === void 0 && $$bindings.theme && theme !== void 0) $$bindings.theme(theme);
	if ($$props.focusButton === void 0 && $$bindings.focusButton && focusButton !== void 0) $$bindings.focusButton(focusButton);
	$$result.css.add(css$5);

	return `<button${add_attribute("aria-expanded", expanded, 0)} class="${escape(null_to_empty(`expand-button ${className}`)) + " svelte-1b75wvq"}" data-event-action="${"click"}"${add_attribute("data-event-category", message, 0)} data-event-label="${"Expand button clicked"}"${add_attribute("data-theme", theme, 0)} data-track="${"click"}" type="${"button"}"${add_attribute("this", buttonElement, 1)}><span>${expanded
	? `${escape(expandedMessage)}`
	: `${escape(message)}`}</span>
  <span class="${"toggle-icon svelte-1b75wvq"}">${validate_component(LogoChevron, "LogoChevron").$$render($$result, { height: "0.3" }, {}, {})}</span></button>`;
});

/* node_modules/nature-immersive-svelte-components/src/components/LogoNature/index.svelte generated by Svelte v3.38.3 */

const css$4 = {
	code: "svg.svelte-fftrry{display:block;overflow:visible}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  export let className = \\\"\\\";\\n  export let height = 1;\\n  export let title = \\\"Nature\\\";\\n</script>\\n\\n<style>\\n  svg {\\n    display: block;\\n    overflow: visible;\\n  }\\n</style>\\n\\n<svg\\n  class=\\\"{className}\\\"\\n  height=\\\"{`${height}em`}\\\"\\n  viewBox=\\\"0 0 200 49\\\"\\n  aria-hidden=\\\"true\\\"\\n  focusable=\\\"false\\\"\\n>\\n  <path\\n    d=\\\"M12.8 8.4l.1.1v8.4h.2c1.7-4.8 6-8.7 12.2-8.7 8.1 0 10.5 4 10.5\\n    11.7v15.2c0 4.6.3 9.4 1.4 13h-13c1.1-3.4 1.2-7.6\\n    1.2-12.6V21.1c0-3.5-1.4-5.2-5.3-5.2-3 0-5.2.8-6.9 2.3v17.4c0 5 .1 9.2 1.2\\n    12.6H1.5c1.2-3.6 1.4-8.4 1.4-13V21.1c0-3.8-1.4-7.2-3-9l12.9-3.7\\\"\\n  ></path>\\n  <path\\n    d=\\\"M59.8 40.7V26.5c-.8 1.2-1.8 1.9-4.7 3.2-3.7 1.8-5 3.8-5 7.9 0 3.4 1.9 5.6\\n    4.9 5.6 3 .1 4-1 4.8-2.5zM56.4 8.3c10.1 0 13.8 4 13.8 12.2v17.2c0 3.1 1.2 4\\n    3.7 4 .4 0 1.7-.2 2.1-.6-.2 1.2-.4 1.8-.6 2.5-1.2 3.4-3.3 5.4-7.5 5.4-5\\n    0-7.5-3.5-7.6-7.1h-.1c-1.7 5-4.9 7.1-10 7.1-6.3 0-10.3-3.8-10.3-9.7 0-6.2\\n    5.6-8.9 11.5-11.2 5.6-2.2 8.6-3.8 8.6-7.8v-.8c0-4.4-1.4-6.6-5.5-6.6-2.6\\n    0-3.5 1.2-4.1 3.7-.8 3.8-2.3 5.1-4.8 5.1-2.2 0-4.3-1.5-4.3-4.3-.2-5.4\\n    7.3-9.1 15.1-9.1z\\\"\\n  ></path>\\n  <path\\n    d=\\\"M98.7 43.9C97.4 47 94.1 49 89.4 49c-8\\n    0-11.1-4-11.1-11.4v-23h-3.8v-.3L88.4 0l.2.1v9.1h10l-1 5.5h-8.9V36c0 4.1 1.7\\n    5.7 5.4 5.7 2.8 0 4.3-.4 5.6-1.1-.3 1.4-.5 2.2-1 3.3\\\"\\n  ></path>\\n  <path\\n    d=\\\"M113.1 8.9v27c0 4 1.6 6.3 5.5 6.3 3.3 0 5.8-1.1\\n    7.2-3V20.9c0-4-.4-7.4-1.7-10.8l12-1.2v27.6c0 6.1.6 8.8 1.6\\n    11.7H126v-7.8h-.1c-1.7 5-4.9 8.6-11.6 8.6-8.5\\n    0-11.6-5.1-11.6-12.8V20.9c0-4-.4-7.4-1.7-10.8l12.1-1.2\\\"\\n  ></path>\\n  <path\\n    d=\\\"M152.5 18.3c1.7-7.2 5-10 9.4-10 4 0 6.1 2.1 6.1 5.4 0 3-1.7 5.4-4.8\\n    5.4-1.8 0-2.9-.8-3.7-1.6-.9-.8-1.5-1.7-2.4-1.7-2.1 0-4.4 3.5-4.4 9.4V35c0\\n    4.8.4 9.6 1.3 13.2h-13c1.2-3.6 1.4-8.4\\n    1.4-13V21.1c0-3.8-1.4-7.2-3-9l12.8-3.7.1.1v9.8h.2\\\"\\n  ></path>\\n  <path\\n    d=\\\"M177.2 24l13.1-1.2c-.1-6.2-1.1-9.9-5.4-9.9-4.4.1-7 3.6-7.7 11.1zm7.8\\n    25c-10 0-18.2-6.6-18.2-19.3 0-12.9 7.9-21.5 18.5-21.5 10.1 0 14.8 6.4 14.8\\n    18.5h-22.9v1.2c0 9.7 5 13.6 11.9 13.6 6.2 0 9-2.5 10.8-4.3l.2.6C198.3 43.6\\n    193.7 49 185 49z\\\"\\n  ></path>\\n</svg>\\n<span class=\\\"visually-hidden\\\">{title}</span>\\n\"],\"names\":[],\"mappings\":\"AAOE,GAAG,cAAC,CAAC,AACH,OAAO,CAAE,KAAK,CACd,QAAQ,CAAE,OAAO,AACnB,CAAC\"}"
};

const LogoNature = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { className = "" } = $$props;
	let { height = 1 } = $$props;
	let { title = "Nature" } = $$props;
	if ($$props.className === void 0 && $$bindings.className && className !== void 0) $$bindings.className(className);
	if ($$props.height === void 0 && $$bindings.height && height !== void 0) $$bindings.height(height);
	if ($$props.title === void 0 && $$bindings.title && title !== void 0) $$bindings.title(title);
	$$result.css.add(css$4);

	return `<svg class="${escape(null_to_empty(className)) + " svelte-fftrry"}"${add_attribute("height", `${height}em`, 0)} viewBox="${"0 0 200 49"}" aria-hidden="${"true"}" focusable="${"false"}"><path d="${"M12.8 8.4l.1.1v8.4h.2c1.7-4.8 6-8.7 12.2-8.7 8.1 0 10.5 4 10.5\n    11.7v15.2c0 4.6.3 9.4 1.4 13h-13c1.1-3.4 1.2-7.6\n    1.2-12.6V21.1c0-3.5-1.4-5.2-5.3-5.2-3 0-5.2.8-6.9 2.3v17.4c0 5 .1 9.2 1.2\n    12.6H1.5c1.2-3.6 1.4-8.4 1.4-13V21.1c0-3.8-1.4-7.2-3-9l12.9-3.7"}"></path><path d="${"M59.8 40.7V26.5c-.8 1.2-1.8 1.9-4.7 3.2-3.7 1.8-5 3.8-5 7.9 0 3.4 1.9 5.6\n    4.9 5.6 3 .1 4-1 4.8-2.5zM56.4 8.3c10.1 0 13.8 4 13.8 12.2v17.2c0 3.1 1.2 4\n    3.7 4 .4 0 1.7-.2 2.1-.6-.2 1.2-.4 1.8-.6 2.5-1.2 3.4-3.3 5.4-7.5 5.4-5\n    0-7.5-3.5-7.6-7.1h-.1c-1.7 5-4.9 7.1-10 7.1-6.3 0-10.3-3.8-10.3-9.7 0-6.2\n    5.6-8.9 11.5-11.2 5.6-2.2 8.6-3.8 8.6-7.8v-.8c0-4.4-1.4-6.6-5.5-6.6-2.6\n    0-3.5 1.2-4.1 3.7-.8 3.8-2.3 5.1-4.8 5.1-2.2 0-4.3-1.5-4.3-4.3-.2-5.4\n    7.3-9.1 15.1-9.1z"}"></path><path d="${"M98.7 43.9C97.4 47 94.1 49 89.4 49c-8\n    0-11.1-4-11.1-11.4v-23h-3.8v-.3L88.4 0l.2.1v9.1h10l-1 5.5h-8.9V36c0 4.1 1.7\n    5.7 5.4 5.7 2.8 0 4.3-.4 5.6-1.1-.3 1.4-.5 2.2-1 3.3"}"></path><path d="${"M113.1 8.9v27c0 4 1.6 6.3 5.5 6.3 3.3 0 5.8-1.1\n    7.2-3V20.9c0-4-.4-7.4-1.7-10.8l12-1.2v27.6c0 6.1.6 8.8 1.6\n    11.7H126v-7.8h-.1c-1.7 5-4.9 8.6-11.6 8.6-8.5\n    0-11.6-5.1-11.6-12.8V20.9c0-4-.4-7.4-1.7-10.8l12.1-1.2"}"></path><path d="${"M152.5 18.3c1.7-7.2 5-10 9.4-10 4 0 6.1 2.1 6.1 5.4 0 3-1.7 5.4-4.8\n    5.4-1.8 0-2.9-.8-3.7-1.6-.9-.8-1.5-1.7-2.4-1.7-2.1 0-4.4 3.5-4.4 9.4V35c0\n    4.8.4 9.6 1.3 13.2h-13c1.2-3.6 1.4-8.4\n    1.4-13V21.1c0-3.8-1.4-7.2-3-9l12.8-3.7.1.1v9.8h.2"}"></path><path d="${"M177.2 24l13.1-1.2c-.1-6.2-1.1-9.9-5.4-9.9-4.4.1-7 3.6-7.7 11.1zm7.8\n    25c-10 0-18.2-6.6-18.2-19.3 0-12.9 7.9-21.5 18.5-21.5 10.1 0 14.8 6.4 14.8\n    18.5h-22.9v1.2c0 9.7 5 13.6 11.9 13.6 6.2 0 9-2.5 10.8-4.3l.2.6C198.3 43.6\n    193.7 49 185 49z"}"></path></svg>
<span class="${"visually-hidden"}">${escape(title)}</span>`;
});

/* node_modules/nature-immersive-svelte-components/src/components/LogoDownloadFile/index.svelte generated by Svelte v3.38.3 */

const css$3 = {
	code: "svg.svelte-fftrry{display:block;overflow:visible}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  export let className = \\\"\\\";\\n  export let height = 1;\\n</script>\\n\\n<style>\\n  svg {\\n    display: block;\\n    overflow: visible;\\n  }\\n</style>\\n\\n<svg\\n  class=\\\"{className}\\\"\\n  height=\\\"{`${height}em`}\\\"\\n  viewBox=\\\"0 0 27 30\\\"\\n  focusable=\\\"false\\\"\\n  aria-hidden=\\\"true\\\"\\n>\\n  <path\\n    d=\\\"M15.2,0c0.9,0,2.2,0.5,2.9,1.2l7.7,7.6c0.7,0.7,1.2,1.9,1.2,2.9v15c0,1.8-1.5,3.3-3.4,3.3H3.4\\n    C1.5,30,0,28.5,0,26.7V3.3C0,1.5,1.5,0,3.4,0L15.2,0z\\n    M15.2,1.7H3.4c-0.9,0-1.7,0.7-1.7,1.7v23.3c0,0.9,0.8,1.7,1.7,1.7h20.3\\n    c0.9,0,1.7-0.8,1.7-1.7v-15c0-0.5-0.4-1.3-0.7-1.7l-7.7-7.6C16.5,2,15.7,1.7,15.2,1.7z\\n    M12.7,8.3c0.5,0,0.8,0.4,0.8,0.8v10.2l2.9-3\\n    c0.3-0.3,0.9-0.3,1.2,0c0.3,0.3,0.3,0.8,0,1.2l-4.4,4.3c-0.3,0.3-0.9,0.3-1.2,0l-4.4-4.3c-0.3-0.3-0.3-0.9,0-1.2\\n    c0.3-0.3,0.9-0.3,1.2,0l2.9,3V9.2C11.8,8.7,12.2,8.3,12.7,8.3z\\\"\\n  ></path>\\n</svg>\\n\"],\"names\":[],\"mappings\":\"AAME,GAAG,cAAC,CAAC,AACH,OAAO,CAAE,KAAK,CACd,QAAQ,CAAE,OAAO,AACnB,CAAC\"}"
};

const LogoDownloadFile = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { className = "" } = $$props;
	let { height = 1 } = $$props;
	if ($$props.className === void 0 && $$bindings.className && className !== void 0) $$bindings.className(className);
	if ($$props.height === void 0 && $$bindings.height && height !== void 0) $$bindings.height(height);
	$$result.css.add(css$3);
	return `<svg class="${escape(null_to_empty(className)) + " svelte-fftrry"}"${add_attribute("height", `${height}em`, 0)} viewBox="${"0 0 27 30"}" focusable="${"false"}" aria-hidden="${"true"}"><path d="${"M15.2,0c0.9,0,2.2,0.5,2.9,1.2l7.7,7.6c0.7,0.7,1.2,1.9,1.2,2.9v15c0,1.8-1.5,3.3-3.4,3.3H3.4\n    C1.5,30,0,28.5,0,26.7V3.3C0,1.5,1.5,0,3.4,0L15.2,0z\n    M15.2,1.7H3.4c-0.9,0-1.7,0.7-1.7,1.7v23.3c0,0.9,0.8,1.7,1.7,1.7h20.3\n    c0.9,0,1.7-0.8,1.7-1.7v-15c0-0.5-0.4-1.3-0.7-1.7l-7.7-7.6C16.5,2,15.7,1.7,15.2,1.7z\n    M12.7,8.3c0.5,0,0.8,0.4,0.8,0.8v10.2l2.9-3\n    c0.3-0.3,0.9-0.3,1.2,0c0.3,0.3,0.3,0.8,0,1.2l-4.4,4.3c-0.3,0.3-0.9,0.3-1.2,0l-4.4-4.3c-0.3-0.3-0.3-0.9,0-1.2\n    c0.3-0.3,0.9-0.3,1.2,0l2.9,3V9.2C11.8,8.7,12.2,8.3,12.7,8.3z"}"></path></svg>`;
});

/* node_modules/nature-immersive-svelte-components/src/components/MenuPdfDownload/index.svelte generated by Svelte v3.38.3 */

const css$2 = {
	code: "a.svelte-vxwq6j{display:flex;align-items:center;gap:var(--s-2)}.no-flexbox-gap a > * + *{margin-left:var(--s-2)}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  import LogoDownloadFile from \\\"../LogoDownloadFile/index.svelte\\\";\\n\\n  export let doi;\\n  export let logoHeight = 1.6;\\n</script>\\n\\n<style>\\n  a {\\n    display: flex;\\n    align-items: center;\\n    gap: var(--s-2);\\n  }\\n\\n  :global(.no-flexbox-gap a > * + *) {\\n    margin-left: var(--s-2);\\n  }\\n</style>\\n\\n<a\\n  data-event-action=\\\"click\\\"\\n  data-event-category=\\\"menu\\\"\\n  data-event-label=\\\"PDF dowload\\\"\\n  data-track=\\\"click\\\"\\n  href={`pdf/${doi}.pdf`}\\n>\\n  <span>PDF download</span>\\n  <span class=\\\"pdf-icon\\\">\\n    <LogoDownloadFile height={logoHeight} />\\n  </span>\\n</a>\\n\"],\"names\":[],\"mappings\":\"AAQE,CAAC,cAAC,CAAC,AACD,OAAO,CAAE,IAAI,CACb,WAAW,CAAE,MAAM,CACnB,GAAG,CAAE,IAAI,KAAK,CAAC,AACjB,CAAC,AAEO,yBAAyB,AAAE,CAAC,AAClC,WAAW,CAAE,IAAI,KAAK,CAAC,AACzB,CAAC\"}"
};

const MenuPdfDownload = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { doi } = $$props;
	let { logoHeight = 1.6 } = $$props;
	if ($$props.doi === void 0 && $$bindings.doi && doi !== void 0) $$bindings.doi(doi);
	if ($$props.logoHeight === void 0 && $$bindings.logoHeight && logoHeight !== void 0) $$bindings.logoHeight(logoHeight);
	$$result.css.add(css$2);

	return `<a data-event-action="${"click"}" data-event-category="${"menu"}" data-event-label="${"PDF dowload"}" data-track="${"click"}"${add_attribute("href", `pdf/${doi}.pdf`, 0)} class="${"svelte-vxwq6j"}"><span>PDF download</span>
  <span class="${"pdf-icon"}">${validate_component(LogoDownloadFile, "LogoDownloadFile").$$render($$result, { height: logoHeight }, {}, {})}</span></a>`;
});

/* node_modules/nature-immersive-svelte-components/src/components/Menu/index.svelte generated by Svelte v3.38.3 */

const css$1 = {
	code: ".menu-container.svelte-seamqm{position:relative;padding:var(--s-2);font-family:var(--sans-serif-font)}a.svelte-seamqm{display:block;max-width:max-content;text-decoration:none}.flex-grow.svelte-seamqm{flex-grow:2;max-width:none}ul.svelte-seamqm{display:flex;align-items:center;justify-content:space-between;max-width:none;padding:0;margin:0;list-style:none}li.svelte-seamqm{padding:var(--s-4)}.skip-link.svelte-seamqm:not(:focus){position:absolute !important;width:1px;height:1px;padding:0 !important;margin:-1px !important;overflow:hidden;clip:rect(0, 0, 0, 0);border:0 !important;opacity:0}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":[\"<script>\\n  import { onMount } from \\\"svelte\\\";\\n  import { menuElement, menuHeight } from \\\"./stores/menu-stores.js\\\";\\n  import MenuList from \\\"../MenuList/index.svelte\\\";\\n  import MenuListStatic from \\\"../MenuListStatic/index.svelte\\\";\\n  import MenuSocialLinks from \\\"../MenuSocialLinks/index.svelte\\\";\\n  import ExpandButton from \\\"../ExpandButton/index.svelte\\\";\\n  import LogoNature from \\\"../LogoNature/index.svelte\\\";\\n  import MenuPdfDownload from \\\"../MenuPdfDownload/index.svelte\\\";\\n\\n  /**\\n   * - menuLinks\\n   * - pdfAvailable\\n   * - doi\\n   */\\n  export let articleData;\\n  let { menuLinks, pdfAvailable, doi } = articleData;\\n\\n  let logoHeight = 1.6;\\n  let mounted = false;\\n  let menuIsExpanded = true;\\n  let menuLinkIsFocused = false;\\n  let buttonIsFocused = false;\\n  let lastMenuLinkElem = null;\\n  let handleButtonBlur;\\n\\n  let closeMenu = () => {\\n    menuIsExpanded = false;\\n  };\\n\\n  let focusButton = () => {\\n    buttonElement.focus();\\n  };\\n\\n  let handleButtonClick = () => {\\n    menuIsExpanded = !menuIsExpanded;\\n  };\\n\\n  let handleMenuLinkFocus = () => {\\n    menuLinkIsFocused = true;\\n  };\\n\\n  let handleButtonFocus = () => {\\n    buttonIsFocused = true;\\n  };\\n\\n  let handleMenuLinkBlur = (event) => {\\n    menuLinkIsFocused = false;\\n\\n    if (event.target === lastMenuLinkElem) {\\n      closeMenu();\\n    }\\n  };\\n\\n  let handleKeydown = (event) => {\\n    let { key } = event;\\n    let escapeIsPressed = key === \\\"Escape\\\";\\n    let menuLinkOrButtonAreFocused = menuLinkIsFocused || buttonIsFocused;\\n\\n    if (escapeIsPressed && menuIsExpanded && menuLinkOrButtonAreFocused) {\\n      closeMenu();\\n      focusButton();\\n    }\\n  };\\n\\n  onMount(() => {\\n    mounted = true;\\n    menuIsExpanded = false;\\n\\n    // `window` is not available for static render,\\n    // so wait till onMount to define this function\\n    // 'blur' event doesn't seem to fire on firefox using MocOS using mouse clicks\\n    // https://github.com/facebook/react/issues/12993#issuecomment-413949427\\n    handleButtonBlur = () => {\\n      window.setTimeout(() => {\\n        if (!menuLinkIsFocused) {\\n          closeMenu();\\n        }\\n      }, 0);\\n    };\\n  });\\n</script>\\n\\n<style>\\n  .menu-container {\\n    position: relative;\\n    padding: var(--s-2);\\n    font-family: var(--sans-serif-font);\\n  }\\n\\n  a {\\n    display: block;\\n    max-width: max-content;\\n    text-decoration: none;\\n  }\\n\\n  .flex-grow {\\n    flex-grow: 2;\\n    max-width: none;\\n  }\\n\\n  ul {\\n    display: flex;\\n    align-items: center;\\n    justify-content: space-between;\\n    max-width: none;\\n    padding: 0;\\n    margin: 0;\\n    list-style: none;\\n  }\\n\\n  li {\\n    padding: var(--s-4);\\n  }\\n\\n  .skip-link:not(:focus) {\\n    /* visibly hidden */\\n    position: absolute !important;\\n    width: 1px;\\n    height: 1px;\\n    padding: 0 !important;\\n    margin: -1px !important;\\n    overflow: hidden;\\n    clip: rect(0, 0, 0, 0);\\n    border: 0 !important;\\n    opacity: 0;\\n  }\\n</style>\\n\\n<svelte:window on:keydown={handleKeydown} />\\n\\n<a href=\\\"#main-content\\\" class=\\\"skip-link font-family:sans-serif\\\">\\n  Skip to main content\\n</a>\\n\\n<header>\\n  <ul\\n    class=\\\"menu-container flex-wrap:wrap\\\"\\n    data-theme=\\\"menu\\\"\\n    bind:this={$menuElement}\\n  >\\n    <li class=\\\"flex-grow\\\">\\n      <a\\n        class=\\\"link-with-svg\\\"\\n        data-event-action=\\\"click\\\"\\n        data-event-category=\\\"menu\\\"\\n        data-event-label=\\\"nature.com\\\"\\n        data-track=\\\"click\\\"\\n        href=\\\"https://www.nature.com\\\"\\n      >\\n        <LogoNature height={logoHeight} />\\n      </a>\\n    </li>\\n\\n    {#if pdfAvailable}\\n      <li><MenuPdfDownload {logoHeight} {doi} /></li>\\n    {/if}\\n\\n    <li>\\n      <MenuSocialLinks {articleData} />\\n    </li>\\n\\n    {#if menuLinks && menuLinks.length}\\n      {#if mounted}\\n        <li>\\n          <ExpandButton\\n            expanded={menuIsExpanded}\\n            expandedMessage=\\\"Menu\\\"\\n            let:buttonElement\\n            message=\\\"Menu\\\"\\n            on:blur={handleButtonBlur}\\n            on:click={handleButtonClick}\\n            on:focus={handleButtonFocus}\\n            theme=\\\"menu\\\"\\n          />\\n          {#if menuIsExpanded}\\n            <MenuList\\n              {logoHeight}\\n              {menuLinks}\\n              bind:lastMenuLinkElem\\n              menuHeight={$menuHeight}\\n              on:blur={handleMenuLinkBlur}\\n              on:focus={handleMenuLinkFocus}\\n            />\\n          {/if}\\n        </li>\\n      {:else}\\n        <li>\\n          <a href=\\\"#menu\\\">Menu</a>\\n        </li>\\n      {/if}\\n    {/if}\\n  </ul>\\n\\n  <slot name=\\\"heading\\\" />\\n</header>\\n\\n<slot />\\n\\n{#if !mounted}\\n  <MenuListStatic {menuLinks} />\\n{/if}\\n\"],\"names\":[],\"mappings\":\"AAoFE,eAAe,cAAC,CAAC,AACf,QAAQ,CAAE,QAAQ,CAClB,OAAO,CAAE,IAAI,KAAK,CAAC,CACnB,WAAW,CAAE,IAAI,iBAAiB,CAAC,AACrC,CAAC,AAED,CAAC,cAAC,CAAC,AACD,OAAO,CAAE,KAAK,CACd,SAAS,CAAE,WAAW,CACtB,eAAe,CAAE,IAAI,AACvB,CAAC,AAED,UAAU,cAAC,CAAC,AACV,SAAS,CAAE,CAAC,CACZ,SAAS,CAAE,IAAI,AACjB,CAAC,AAED,EAAE,cAAC,CAAC,AACF,OAAO,CAAE,IAAI,CACb,WAAW,CAAE,MAAM,CACnB,eAAe,CAAE,aAAa,CAC9B,SAAS,CAAE,IAAI,CACf,OAAO,CAAE,CAAC,CACV,MAAM,CAAE,CAAC,CACT,UAAU,CAAE,IAAI,AAClB,CAAC,AAED,EAAE,cAAC,CAAC,AACF,OAAO,CAAE,IAAI,KAAK,CAAC,AACrB,CAAC,AAED,wBAAU,KAAK,MAAM,CAAC,AAAC,CAAC,AAEtB,QAAQ,CAAE,QAAQ,CAAC,UAAU,CAC7B,KAAK,CAAE,GAAG,CACV,MAAM,CAAE,GAAG,CACX,OAAO,CAAE,CAAC,CAAC,UAAU,CACrB,MAAM,CAAE,IAAI,CAAC,UAAU,CACvB,QAAQ,CAAE,MAAM,CAChB,IAAI,CAAE,KAAK,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CACtB,MAAM,CAAE,CAAC,CAAC,UAAU,CACpB,OAAO,CAAE,CAAC,AACZ,CAAC\"}"
};

let logoHeight = 1.6;

const Menu = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $menuElement, $$unsubscribe_menuElement;
	let $menuHeight, $$unsubscribe_menuHeight;
	$$unsubscribe_menuElement = subscribe(menuElement, value => $menuElement = value);
	$$unsubscribe_menuHeight = subscribe(menuHeight, value => $menuHeight = value);
	let { articleData } = $$props;
	let { menuLinks, pdfAvailable, doi } = articleData;
	let mounted = false;
	let menuIsExpanded = true;
	let lastMenuLinkElem = null;

	onMount(() => {
		mounted = true;
		menuIsExpanded = false;
	});

	if ($$props.articleData === void 0 && $$bindings.articleData && articleData !== void 0) $$bindings.articleData(articleData);
	$$result.css.add(css$1);
	let $$settled;
	let $$rendered;

	do {
		$$settled = true;

		$$rendered = `

<a href="${"#main-content"}" class="${"skip-link font-family:sans-serif svelte-seamqm"}">Skip to main content
</a>

<header><ul class="${"menu-container flex-wrap:wrap svelte-seamqm"}" data-theme="${"menu"}"${add_attribute("this", $menuElement, 1)}><li class="${"flex-grow svelte-seamqm"}"><a class="${"link-with-svg svelte-seamqm"}" data-event-action="${"click"}" data-event-category="${"menu"}" data-event-label="${"nature.com"}" data-track="${"click"}" href="${"https://www.nature.com"}">${validate_component(LogoNature, "LogoNature").$$render($$result, { height: logoHeight }, {}, {})}</a></li>

    ${pdfAvailable
		? `<li class="${"svelte-seamqm"}">${validate_component(MenuPdfDownload, "MenuPdfDownload").$$render($$result, { logoHeight, doi }, {}, {})}</li>`
		: ``}

    <li class="${"svelte-seamqm"}">${validate_component(MenuSocialLinks, "MenuSocialLinks").$$render($$result, { articleData }, {}, {})}</li>

    ${menuLinks && menuLinks.length
		? `${mounted
			? `<li class="${"svelte-seamqm"}">${validate_component(ExpandButton, "ExpandButton").$$render(
					$$result,
					{
						expanded: menuIsExpanded,
						expandedMessage: "Menu",
						message: "Menu",
						theme: "menu"
					},
					{},
					{}
				)}
          ${menuIsExpanded
				? `${validate_component(MenuList, "MenuList").$$render(
						$$result,
						{
							logoHeight,
							menuLinks,
							menuHeight: $menuHeight,
							lastMenuLinkElem
						},
						{
							lastMenuLinkElem: $$value => {
								lastMenuLinkElem = $$value;
								$$settled = false;
							}
						},
						{}
					)}`
				: ``}</li>`
			: `<li class="${"svelte-seamqm"}"><a href="${"#menu"}" class="${"svelte-seamqm"}">Menu</a></li>`}`
		: ``}</ul>

  ${slots.heading ? slots.heading({}) : ``}</header>

${slots.default ? slots.default({}) : ``}

${!mounted
		? `${validate_component(MenuListStatic, "MenuListStatic").$$render($$result, { menuLinks }, {}, {})}`
		: ``}`;
	} while (!$$settled);

	$$unsubscribe_menuElement();
	$$unsubscribe_menuHeight();
	return $$rendered;
});

// The initial value is false as we don't know what the
// readers preferences will be
const allowAnimation = writable(false);

/* src/App.svelte generated by Svelte v3.38.3 */

const css = {
	code: "body{--global-stack-space:var(--s3)}.heading{margin-top:var(--global-stack-space)}main.svelte-19032c{margin:var(--global-stack-space)}",
	map: "{\"version\":3,\"file\":\"App.svelte\",\"sources\":[\"App.svelte\"],\"sourcesContent\":[\"<script>\\n  import { onMount } from \\\"svelte\\\";\\n  import {\\n    Footer,\\n    Head,\\n    Heading,\\n    Menu,\\n  } from \\\"nature-immersive-svelte-components\\\";\\n  import { Stack, Center } from \\\"creditdesign-svelte-components\\\";\\n  import { allowAnimation } from \\\"./stores/prefers-reduced-motion.js\\\";\\n\\n  export let data;\\n\\n  let { articleData } = data;\\n\\n  let mounted = false;\\n\\n  onMount(() => {\\n    mounted = true;\\n    // allowAnimation should be true if the reader has set 'no-preference'\\n    // otherwise it should be false, and this should stop the animations\\n    // from being loaded\\n    let QUERY = \\\"(prefers-reduced-motion: no-preference)\\\";\\n    allowAnimation.set(window.matchMedia(QUERY).matches);\\n  });\\n</script>\\n\\n<style>\\n  :global(body) {\\n    --global-stack-space: var(--s3);\\n  }\\n\\n  :global(.heading) {\\n    margin-top: var(--global-stack-space);\\n  }\\n\\n  main {\\n    margin: var(--global-stack-space);\\n  }\\n</style>\\n\\n<Head articleData=\\\"{articleData}\\\" />\\n\\n<Menu articleData=\\\"{articleData}\\\">\\n  <div slot=\\\"heading\\\">\\n    <Heading articleData=\\\"{articleData}\\\" />\\n  </div>\\n\\n  <main id=\\\"main-content\\\" tabindex=\\\"-1\\\">\\n    <Center>\\n      <Stack>\\n        <p>Hello and welcome to the Nature immersive article template.</p>\\n        <p>Please use these files to start your project.</p>\\n        {#if mounted}\\n          <p>NB: The javascript has loaded.</p>\\n        {/if}\\n      </Stack>\\n    </Center>\\n  </main>\\n</Menu>\\n<Footer />\\n\"],\"names\":[],\"mappings\":\"AA4BU,IAAI,AAAE,CAAC,AACb,oBAAoB,CAAE,SAAS,AACjC,CAAC,AAEO,QAAQ,AAAE,CAAC,AACjB,UAAU,CAAE,IAAI,oBAAoB,CAAC,AACvC,CAAC,AAED,IAAI,cAAC,CAAC,AACJ,MAAM,CAAE,IAAI,oBAAoB,CAAC,AACnC,CAAC\"}"
};

const App = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { data } = $$props;
	let { articleData } = data;
	let mounted = false;

	onMount(() => {
		mounted = true;

		// allowAnimation should be true if the reader has set 'no-preference'
		// otherwise it should be false, and this should stop the animations
		// from being loaded
		let QUERY = "(prefers-reduced-motion: no-preference)";

		allowAnimation.set(window.matchMedia(QUERY).matches);
	});

	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
	$$result.css.add(css);

	return `${validate_component(Head, "Head").$$render($$result, { articleData }, {}, {})}

${validate_component(Menu, "Menu").$$render($$result, { articleData }, {}, {
		heading: () => `<div slot="${"heading"}">${validate_component(Heading, "Heading").$$render($$result, { articleData }, {}, {})}</div>`,
		default: () => `<main id="${"main-content"}" tabindex="${"-1"}" class="${"svelte-19032c"}">${validate_component(Center, "Center").$$render($$result, {}, {}, {
			default: () => `${validate_component(Stack, "Stack").$$render($$result, {}, {}, {
				default: () => `<p>Hello and welcome to the Nature immersive article template.</p>
        <p>Please use these files to start your project.</p>
        ${mounted ? `<p>NB: The javascript has loaded.</p>` : ``}`
			})}`
		})}</main>`
	})}
${validate_component(Footer, "Footer").$$render($$result, {}, {}, {})}`;
});

module.exports = App;
